; ========================================================================
; Disassembly of archive/deskmate-3.05/extracted/INSTALL.EXE
; Generated by disasm_mz.py (Bayside project)
; ========================================================================

; MZ Header:
;   File size:        828 bytes
;   Header size:      512 bytes
;   Code size:        316 bytes
;   Pages:            2
;   Relocations:      2
;   Entry point:      0000:000C
;   Init SS:SP:       0018:0800
;   Min alloc:        0x0079 paragraphs
;   Max alloc:        0x0079 paragraphs
;   DM89 signature:   present
;   DM89 raw:         444d38393c0000000000000000000000000000000000000000000000000000002b00

; Segment Map:
;   seg_0000  file=0x0200  (CODE/DATA)
;   seg_000A  file=0x02A0  (CODE/DATA)
;   seg_0018  file=0x0380  (BSS)

; Relocation Table (2 entries):
;   000A:002B  file=0x02CB  value=seg_000A
;   0000:000D  file=0x020D  value=seg_000A

; String Table:
;   000A:0003 (0x02A3): "DDESK.EXE"
;   000A:0011 (0x02B1): "MOLDAPP.MOD"
;   000A:001D (0x02BD): "INSTALL"
;   000A:003D (0x02DD): "Please change to the drive containing the DESKMATE 1 disk\r\nbef..."
;   000A:0093 (0x0333): "$$$$$$$$$"

; Analysis Summary:
;   Instructions:     60
;   Functions (CALL): 0
;   Jump targets:     2
;   Strings:          5
;   INT calls:        7

; ========================================================================
; CODE / DATA
; ========================================================================

; ------------------------------------------------------------------------
; SEGMENT seg_0000  (160 bytes, file 0x0200-0x02A0)
; ------------------------------------------------------------------------
seg_0000:


loc_0000_0000:
  0000:0000  ba3d00            mov      dx, 0x3d
  0000:0003  b409              mov      ah, 9
  0000:0005  cd21              int      0x21  ; INT 21h/09h: Print string (DS:DX)
  0000:0007  b8004c            mov      ax, 0x4c00
  0000:000A  cd21              int      0x21  ; INT 21h/4Ch: Exit with return code

entry_point:
  0000:000C  b80a00            mov      ax, 0xa  ; RELOC->seg_000A
  0000:000F  8ed8              mov      ds, ax
  0000:0011  8ec0              mov      es, ax
  0000:0013  ba0400            mov      dx, 4
  0000:0016  b8003d            mov      ax, 0x3d00
  0000:0019  cd21              int      0x21  ; INT 21h/3Dh: Open file
  0000:001B  72e3              jb       0  ; -> loc_0000_0000
  0000:001D  8bd8              mov      bx, ax
  0000:001F  b93c00            mov      cx, 0x3c
  0000:0022  ba9c00            mov      dx, 0x9c
  0000:0025  b43f              mov      ah, 0x3f
  0000:0027  cd21              int      0x21  ; INT 21h/3Fh: Read file
  0000:0029  72d5              jb       0  ; -> loc_0000_0000
  0000:002B  b43e              mov      ah, 0x3e
  0000:002D  cd21              int      0x21  ; INT 21h/3Eh: Close file
  0000:002F  833eb40025        cmp      word ptr [0xb4], 0x25
  0000:0034  76ca              jbe      0  ; -> loc_0000_0000
  0000:0036  813eb800444d      cmp      word ptr [0xb8], 0x4d44
  0000:003C  75c2              jne      0  ; -> loc_0000_0000
  0000:003E  813eba003839      cmp      word ptr [0xba], 0x3938
  0000:0044  75ba              jne      0  ; -> loc_0000_0000
  0000:0046  a10200            mov      ax, word ptr [2]
  0000:0049  3906b600          cmp      word ptr [0xb6], ax
  0000:004D  75b1              jne      0  ; -> loc_0000_0000
  0000:004F  ba0400            mov      dx, 4
  0000:0052  bb2700            mov      bx, 0x27
  0000:0055  b8014b            mov      ax, 0x4b01
  0000:0058  cd21              int      0x21  ; INT 21h/4Bh: EXEC (load/execute)
  0000:005A  72a4              jb       0  ; -> loc_0000_0000
  0000:005C  b451              mov      ah, 0x51
  0000:005E  cd21              int      0x21  ; INT 21h/51h: Get PSP
  0000:0060  8ec3              mov      es, bx
  0000:0062  26c7060a000700    mov      word ptr es:[0xa], 7
  0000:0069  268c0e0c00        mov      word ptr es:[0xc], cs
  0000:006E  bf0001            mov      di, 0x100
  0000:0071  b044              mov      al, 0x44

loc_0000_0073:
  0000:0073  b9ffff            mov      cx, 0xffff
  0000:0076  f2ae              repne scasb al, byte ptr es:[di]
  0000:0078  be1100            mov      si, 0x11
  0000:007B  b90c00            mov      cx, 0xc
  0000:007E  f3a6              repe cmpsb byte ptr [si], byte ptr es:[di]
  0000:0080  75f1              jne      0x73  ; -> loc_0000_0073
  0000:0082  be1d00            mov      si, 0x1d
  0000:0085  b90800            mov      cx, 8
  0000:0088  83ef16            sub      di, 0x16
  0000:008B  f3a4              rep movsb byte ptr es:[di], byte ptr [si]
  0000:008D  fa                cli      
  0000:008E  8b263500          mov      sp, word ptr [0x35]
  0000:0092  8e163700          mov      ss, word ptr [0x37]
  0000:0096  fb                sti      
  0000:0097  ff363b00          push     word ptr [0x3b]
  0000:009B  ff363900          push     word ptr [0x39]
  0000:009F  06                push     es

; ------------------------------------------------------------------------
; SEGMENT seg_000A  (156 bytes, file 0x02A0-0x033C)
; ------------------------------------------------------------------------
seg_000A:

  000A:0000  1f                pop      ds
  000A:0001  cb                retf     
  000A:0002  db 13                                              ; |.|
  000A:0003  db 44 44 45 53 4B 2E 45 58 45                      ; "DDESK.EXE"
  000A:000C  db 00                                                ; NUL
  000A:000D  db 00 00 00 00                                     ; |....|
  000A:0011  db 4D 4F 4C 44 41 50 50 2E 4D 4F 44                ; "MOLDAPP.MOD"
  000A:001C  db 00                                                ; NUL
  000A:001D  db 49 4E 53 54 41 4C 4C                            ; "INSTALL"
  000A:0024  db 00                                                ; NUL
  000A:0025  db 00 0D 00 00 25 00 0A 00 00 00 00 00 00 00 00 00 ; |....%...........| [RELOC->seg_000A]
  000A:0035  db 01 00 00 00 00 00 00 00                         ; |........|
  000A:003D  db 50 6C 65 61 73 65 20 63 68 61 6E 67 65 20 74 6F ; "Please change to the drive containing the DESKMATE 1 disk\r\..."
  000A:004D  db 20 74 68 65 20 64 72 69 76 65 20 63 6F 6E 74 61
  000A:005D  db 69 6E 69 6E 67 20 74 68 65 20 44 45 53 4B 4D 41
  000A:006D  db 54 45 20 31 20 64 69 73 6B 0D 0A 62 65 66 6F 72
  000A:007D  db 65 20 72 75 6E 6E 69 6E 67 20 69 6E 73 74 61 6C
  000A:008D  db 6C 2E 0D 0A 24
  000A:0092  db 00                                                ; NUL
  000A:0093  db 24 24 24 24 24 24 24 24 24                      ; "$$$$$$$$$"