; Raw disassembly of DMDRWPRT.ACC
; Generated by batch_disasm_acc.py
;
; File size: 1638 bytes
; Load image: 1126 bytes
; Entry point: 003B:0002 (linear 0x003B2)
; SS:SP: 0047:0800
; Relocations: 7
; Imports: (none)
; Segments: 0000, 003B, 0047, 00C7
; Functions: 18
; DM flags: 0x0000
;
; Notable strings found in load image:
;   0x002B8: "=D!~"
;   0x0033F: "F<7X"
;   0x0034A: "!u9VWQR"
;   0x0036B: "NOGF"
;   0x00382: "ZY_^"
;   0x003B2: "01.02"
;   0x003B9: "DRWPRTFILE"
;   0x003C4: "PRINT_INFO"
;   0x003F2: "PRGUF"
;   0x003FC: "DMGUF"
;   0x00410: "DMCSR"
;   0x0041A: "1000CGA"
;   0x00422: "DDGAEGA"
;   0x0042A: "HERCPLANTC16TC4"
;   0x0043E: "MCGAEGA"
;   0x00446: "LREST256TC40H"
;

  00000  b83b00         mov      ax, 0x3b  ; 0000:0000
  00003  8ed8           mov      ds, ax  ; 0000:0003
  00005  fa             cli        ; 0000:0005
  00006  8ed0           mov      ss, ax  ; 0000:0006
  00008  bcc008         mov      sp, 0x8c0  ; 0000:0008
  0000B  fb             sti        ; 0000:000B
  0000C  bbc700         mov      bx, 0xc7  ; 0000:000C
  0000F  81eb0000       sub      bx, 0  ; 0000:000F
  00013  43             inc      bx  ; 0000:0013
  00014  83c310         add      bx, 0x10  ; 0000:0014
  00017  b44a           mov      ah, 0x4a  ; 0000:0017
  00019  cd21           int      0x21  ; 0000:0019
  0001B  e80302         call     sub_00221  ; 0000:001B
  0001E  e8e100         call     sub_00102  ; 0000:001E
  00021  bb3100         mov      bx, 0x31  ; 0000:0021
  00024  c7070900       mov      word ptr [bx], 9  ; 0000:0024
  00028  c747020000     mov      word ptr [bx + 2], 0  ; 0000:0028
  0002D  c6470403       mov      byte ptr [bx + 4], 3  ; 0000:002D
  00031  c747051400     mov      word ptr [bx + 5], 0x14  ; 0000:0031
  00036  53             push     bx  ; 0000:0036
  00037  e8b301         call     sub_001ED  ; 0000:0037
  0003A  83c402         add      sp, 2  ; 0000:003A
  0003D  3dffff         cmp      ax, 0xffff  ; 0000:003D
  00040  7452           je       loc_00094  ; 0000:0040
  00042  c47707         les      si, ptr [bx + 7]  ; 0000:0042
  00045  b80700         mov      ax, 7  ; 0000:0045
  00048  50             push     ax  ; 0000:0048
  00049  e8a701         call     sub_001F3  ; 0000:0049
  0004C  83c402         add      sp, 2  ; 0000:004C
  0004F  26894416       mov      word ptr es:[si + 0x16], ax  ; 0000:004F
  00053  3dffff         cmp      ax, 0xffff  ; 0000:0053
  00056  7439           je       loc_00091  ; 0000:0056
  00058  3d0000         cmp      ax, 0  ; 0000:0058
  0005B  7434           je       loc_00091  ; 0000:005B
  0005D  b81f00         mov      ax, 0x1f  ; 0000:005D
  00060  50             push     ax  ; 0000:0060
  00061  e80502         call     sub_00269  ; 0000:0061
  00064  83c402         add      sp, 2  ; 0000:0064
  00067  b80000         mov      ax, 0  ; 0000:0067
  0006A  50             push     ax  ; 0000:006A
  0006B  e8e901         call     sub_00257  ; 0000:006B
  0006E  83c402         add      sp, 2  ; 0000:006E
  00071  32e4           xor      ah, ah  ; 0000:0071
  00073  a02f00         mov      al, byte ptr [0x2f]  ; 0000:0073
  00076  50             push     ax  ; 0000:0076
  00077  33c0           xor      ax, ax  ; 0000:0077
  00079  50             push     ax  ; 0000:0079
  0007A  26ff34         push     word ptr es:[si]  ; 0000:007A
  0007D  e8fb01         call     sub_0027B  ; 0000:007D
  00080  83c406         add      sp, 6  ; 0000:0080
  00083  26ff7402       push     word ptr es:[si + 2]  ; 0000:0083
  00087  b80100         mov      ax, 1  ; 0000:0087
  0008A  50             push     ax  ; 0000:008A
  0008B  e8cf01         call     sub_0025D  ; 0000:008B
  0008E  83c404         add      sp, 4  ; 0000:008E
loc_00091:
  00091  e8cf01         call     sub_00263  ; 0000:0091
loc_00094:
  00094  e8ad00         call     sub_00144  ; 0000:0094
  00097  e88e01         call     sub_00228  ; 0000:0097
  0009A  b44c           mov      ah, 0x4c  ; 0000:009A
  0009C  b000           mov      al, 0  ; 0000:009C
  0009E  cd21           int      0x21  ; 0000:009E
  000A0  06             push     es  ; 0000:00A0
  000A1  53             push     bx  ; 0000:00A1
  000A2  1e             push     ds  ; 0000:00A2
  000A3  07             pop      es  ; 0000:00A3
  000A4  b80802         mov      ax, 0x208  ; 0000:00A4
  000A7  ba4200         mov      dx, 0x42  ; 0000:00A7
  000AA  bb3e00         mov      bx, 0x3e  ; 0000:00AA
  000AD  cde0           int      0xe0  ; 0000:00AD
  000AF  0bc0           or       ax, ax  ; 0000:00AF
  000B1  7e16           jle      loc_000C9  ; 0000:00B1
loc_000B3:
  000B3  c606520001     mov      byte ptr [0x52], 1  ; 0000:00B3
loc_000B8:
  000B8  b80602         mov      ax, 0x206  ; 0000:00B8
  000BB  cde0           int      0xe0  ; 0000:00BB
  000BD  0bc0           or       ax, ax  ; 0000:00BD
  000BF  b8ffff         mov      ax, 0xffff  ; 0000:00BF
  000C2  7402           je       loc_000C6  ; 0000:00C2
  000C4  33c0           xor      ax, ax  ; 0000:00C4
loc_000C6:
  000C6  5b             pop      bx  ; 0000:00C6
  000C7  07             pop      es  ; 0000:00C7
  000C8  c3             ret        ; 0000:00C8
loc_000C9:
  000C9  ba4c00         mov      dx, 0x4c  ; 0000:00C9
  000CC  b80802         mov      ax, 0x208  ; 0000:00CC
  000CF  cde0           int      0xe0  ; 0000:00CF
  000D1  0bc0           or       ax, ax  ; 0000:00D1
  000D3  7ede           jle      loc_000B3  ; 0000:00D3
  000D5  c606520000     mov      byte ptr [0x52], 0  ; 0000:00D5
  000DA  ebdc           jmp      loc_000B8  ; 0000:00DA
  000DC  52             push     dx  ; 0000:00DC
  000DD  06             push     es  ; 0000:00DD
  000DE  803e520000     cmp      byte ptr [0x52], 0  ; 0000:00DE
  000E3  7405           je       loc_000EA  ; 0000:00E3
  000E5  ba4200         mov      dx, 0x42  ; 0000:00E5
  000E8  eb03           jmp      loc_000ED  ; 0000:00E8
loc_000EA:
  000EA  ba4c00         mov      dx, 0x4c  ; 0000:00EA
loc_000ED:
  000ED  b80702         mov      ax, 0x207  ; 0000:00ED
  000F0  1e             push     ds  ; 0000:00F0
  000F1  07             pop      es  ; 0000:00F1
  000F2  cde0           int      0xe0  ; 0000:00F2
  000F4  b86801         mov      ax, 0x168  ; 0000:00F4
  000F7  a33e00         mov      word ptr [0x3e], ax  ; 0000:00F7
  000FA  8cc8           mov      ax, cs  ; 0000:00FA
  000FC  a34000         mov      word ptr [0x40], ax  ; 0000:00FC
  000FF  07             pop      es  ; 0000:00FF
  00100  5a             pop      dx  ; 0000:0100
  00101  c3             ret        ; 0000:0101

; ---- sub_00102 ----
sub_00102:
  00102  06             push     es  ; 0000:0102
  00103  53             push     bx  ; 0000:0103
  00104  1e             push     ds  ; 0000:0104
  00105  07             pop      es  ; 0000:0105
  00106  ba4c00         mov      dx, 0x4c  ; 0000:0106
  00109  bb4800         mov      bx, 0x48  ; 0000:0109
  0010C  b80602         mov      ax, 0x206  ; 0000:010C
  0010F  cde0           int      0xe0  ; 0000:010F
  00111  0bc0           or       ax, ax  ; 0000:0111
  00113  b8ffff         mov      ax, 0xffff  ; 0000:0113
  00116  7429           je       loc_00141  ; 0000:0116
  00118  a14800         mov      ax, word ptr [0x48]  ; 0000:0118
  0011B  a33e00         mov      word ptr [0x3e], ax  ; 0000:011B
  0011E  a14a00         mov      ax, word ptr [0x4a]  ; 0000:011E
  00121  a34000         mov      word ptr [0x40], ax  ; 0000:0121
  00124  b80802         mov      ax, 0x208  ; 0000:0124
  00127  ba4200         mov      dx, 0x42  ; 0000:0127
  0012A  bb3e00         mov      bx, 0x3e  ; 0000:012A
  0012D  cde0           int      0xe0  ; 0000:012D
  0012F  0bc0           or       ax, ax  ; 0000:012F
  00131  7e07           jle      loc_0013A  ; 0000:0131
  00133  c606520001     mov      byte ptr [0x52], 1  ; 0000:0133
  00138  eb05           jmp      loc_0013F  ; 0000:0138
loc_0013A:
  0013A  c606520000     mov      byte ptr [0x52], 0  ; 0000:013A
loc_0013F:
  0013F  33c0           xor      ax, ax  ; 0000:013F
loc_00141:
  00141  5b             pop      bx  ; 0000:0141
  00142  07             pop      es  ; 0000:0142
  00143  c3             ret        ; 0000:0143

; ---- sub_00144 ----
sub_00144:
  00144  52             push     dx  ; 0000:0144
  00145  ba4c00         mov      dx, 0x4c  ; 0000:0145
  00148  b80702         mov      ax, 0x207  ; 0000:0148
  0014B  06             push     es  ; 0000:014B
  0014C  1e             push     ds  ; 0000:014C
  0014D  07             pop      es  ; 0000:014D
  0014E  cde0           int      0xe0  ; 0000:014E
  00150  07             pop      es  ; 0000:0150
  00151  b86401         mov      ax, 0x164  ; 0000:0151
  00154  a34800         mov      word ptr [0x48], ax  ; 0000:0154
  00157  a33e00         mov      word ptr [0x3e], ax  ; 0000:0157
  0015A  8cc8           mov      ax, cs  ; 0000:015A
  0015C  a34a00         mov      word ptr [0x4a], ax  ; 0000:015C
  0015F  a34000         mov      word ptr [0x40], ax  ; 0000:015F
  00162  5a             pop      dx  ; 0000:0162
  00163  c3             ret        ; 0000:0163
  00164  b8ffff         mov      ax, 0xffff  ; 0000:0164
  00167  cb             retf       ; 0000:0167
  00168  b8ffff         mov      ax, 0xffff  ; 0000:0168
  0016B  cb             retf       ; 0000:016B
loc_0016C:
  0016C  803e520001     cmp      byte ptr [0x52], 1  ; 0000:016C
  00171  7411           je       loc_00184  ; 0000:0171
  00173  3d3900         cmp      ax, 0x39  ; 0000:0173
  00176  7c0c           jl       loc_00184  ; 0000:0176
  00178  7407           je       loc_00181  ; 0000:0178
  0017A  3d4400         cmp      ax, 0x44  ; 0000:017A
  0017D  7e2c           jle      loc_001AB  ; 0000:017D
  0017F  eb03           jmp      loc_00184  ; 0000:017F
loc_00181:
  00181  b8ae00         mov      ax, 0xae  ; 0000:0181
loc_00184:
  00184  8f065700       pop      word ptr [0x57]  ; 0000:0184
  00188  ff365500       push     word ptr [0x55]  ; 0000:0188
  0018C  ff365700       push     word ptr [0x57]  ; 0000:018C
  00190  53             push     bx  ; 0000:0190
  00191  8bdc           mov      bx, sp  ; 0000:0191
  00193  1e             push     ds  ; 0000:0193
  00194  06             push     es  ; 0000:0194
  00195  16             push     ss  ; 0000:0195
  00196  07             pop      es  ; 0000:0196
  00197  ff1e3e00       lcall    [0x3e]  ; 0000:0197
  0019B  07             pop      es  ; 0000:019B
  0019C  1f             pop      ds  ; 0000:019C
  0019D  5b             pop      bx  ; 0000:019D
  0019E  8f065700       pop      word ptr [0x57]  ; 0000:019E
  001A2  8f065500       pop      word ptr [0x55]  ; 0000:01A2
  001A6  ff365700       push     word ptr [0x57]  ; 0000:01A6
loc_001AA:
  001AA  c3             ret        ; 0000:01AA
loc_001AB:
  001AB  b8ffff         mov      ax, 0xffff  ; 0000:01AB
  001AE  ebfa           jmp      loc_001AA  ; 0000:01AE
loc_001B0:
  001B0  803e520001     cmp      byte ptr [0x52], 1  ; 0000:01B0
  001B5  740a           je       loc_001C1  ; 0000:01B5
  001B7  3dbe00         cmp      ax, 0xbe  ; 0000:01B7
  001BA  742c           je       loc_001E8  ; 0000:01BA
  001BC  3dbf00         cmp      ax, 0xbf  ; 0000:01BC
  001BF  7427           je       loc_001E8  ; 0000:01BF
loc_001C1:
  001C1  8f065700       pop      word ptr [0x57]  ; 0000:01C1
  001C5  ff365500       push     word ptr [0x55]  ; 0000:01C5
  001C9  ff365700       push     word ptr [0x57]  ; 0000:01C9
  001CD  53             push     bx  ; 0000:01CD
  001CE  8bdc           mov      bx, sp  ; 0000:01CE
  001D0  1e             push     ds  ; 0000:01D0
  001D1  06             push     es  ; 0000:01D1
  001D2  16             push     ss  ; 0000:01D2
  001D3  07             pop      es  ; 0000:01D3
  001D4  ff1e4800       lcall    [0x48]  ; 0000:01D4
  001D8  07             pop      es  ; 0000:01D8
  001D9  1f             pop      ds  ; 0000:01D9
  001DA  5b             pop      bx  ; 0000:01DA
  001DB  8f065700       pop      word ptr [0x57]  ; 0000:01DB
  001DF  8f065500       pop      word ptr [0x55]  ; 0000:01DF
  001E3  ff365700       push     word ptr [0x57]  ; 0000:01E3
loc_001E7:
  001E7  c3             ret        ; 0000:01E7
loc_001E8:
  001E8  b8ffff         mov      ax, 0xffff  ; 0000:01E8
  001EB  ebfa           jmp      loc_001E7  ; 0000:01EB

; ---- sub_001ED ----
sub_001ED:
  001ED  b80c00         mov      ax, 0xc  ; 0000:01ED
  001F0  e979ff         jmp      loc_0016C  ; 0000:01F0

; ---- sub_001F3 ----
sub_001F3:
  001F3  b8b300         mov      ax, 0xb3  ; 0000:01F3
  001F6  e9b7ff         jmp      loc_001B0  ; 0000:01F6

; ---- sub_001F9 ----
sub_001F9:
  001F9  06             push     es  ; 0000:01F9
  001FA  53             push     bx  ; 0000:01FA
  001FB  52             push     dx  ; 0000:01FB
  001FC  1e             push     ds  ; 0000:01FC
  001FD  07             pop      es  ; 0000:01FD
  001FE  bb5c00         mov      bx, 0x5c  ; 0000:01FE
  00201  ba6000         mov      dx, 0x60  ; 0000:0201
  00204  b80602         mov      ax, 0x206  ; 0000:0204
  00207  cde0           int      0xe0  ; 0000:0207
  00209  9a81020000     lcall    0, 0x281  ; 0000:0209
  0020E  5a             pop      dx  ; 0000:020E
  0020F  5b             pop      bx  ; 0000:020F
  00210  07             pop      es  ; 0000:0210
  00211  c3             ret        ; 0000:0211

; ---- sub_00212 ----
sub_00212:
  00212  06             push     es  ; 0000:0212
  00213  52             push     dx  ; 0000:0213
  00214  1e             push     ds  ; 0000:0214
  00215  07             pop      es  ; 0000:0215
  00216  ba6000         mov      dx, 0x60  ; 0000:0216
  00219  b80702         mov      ax, 0x207  ; 0000:0219
  0021C  cde0           int      0xe0  ; 0000:021C
  0021E  5a             pop      dx  ; 0000:021E
  0021F  07             pop      es  ; 0000:021F
  00220  c3             ret        ; 0000:0220

; ---- sub_00221 ----
sub_00221:
  00221  e8d5ff         call     sub_001F9  ; 0000:0221
  00224  e84800         call     sub_0026F  ; 0000:0224
  00227  c3             ret        ; 0000:0227

; ---- sub_00228 ----
sub_00228:
  00228  e84a00         call     sub_00275  ; 0000:0228
  0022B  e8e4ff         call     sub_00212  ; 0000:022B
  0022E  c3             ret        ; 0000:022E

; ---- sub_0022F ----
sub_0022F:
  0022F  55             push     bp  ; 0000:022F
  00230  8bec           mov      bp, sp  ; 0000:0230
  00232  83c504         add      bp, 4  ; 0000:0232
  00235  9aa8020000     lcall    0, 0x2a8  ; 0000:0235
  0023A  3dffff         cmp      ax, 0xffff  ; 0000:023A
  0023D  7416           je       loc_00255  ; 0000:023D
  0023F  3dfeff         cmp      ax, 0xfffe  ; 0000:023F
  00242  7411           je       loc_00255  ; 0000:0242
  00244  9ad7020000     lcall    0, 0x2d7  ; 0000:0244
  00249  a36600         mov      word ptr [0x66], ax  ; 0000:0249
  0024C  ff1e5c00       lcall    [0x5c]  ; 0000:024C
  00250  9a01030000     lcall    0, 0x301  ; 0000:0250
loc_00255:
  00255  5d             pop      bp  ; 0000:0255
  00256  c3             ret        ; 0000:0256

; ---- sub_00257 ----
sub_00257:
  00257  b8a320         mov      ax, 0x20a3  ; 0000:0257
  0025A  e9d2ff         jmp      sub_0022F  ; 0000:025A

; ---- sub_0025D ----
sub_0025D:
  0025D  b8a520         mov      ax, 0x20a5  ; 0000:025D
  00260  e9ccff         jmp      sub_0022F  ; 0000:0260

; ---- sub_00263 ----
sub_00263:
  00263  b8ac20         mov      ax, 0x20ac  ; 0000:0263
  00266  e9c6ff         jmp      sub_0022F  ; 0000:0266

; ---- sub_00269 ----
sub_00269:
  00269  b8d020         mov      ax, 0x20d0  ; 0000:0269
  0026C  e9c0ff         jmp      sub_0022F  ; 0000:026C

; ---- sub_0026F ----
sub_0026F:
  0026F  b8d620         mov      ax, 0x20d6  ; 0000:026F
  00272  e9baff         jmp      sub_0022F  ; 0000:0272

; ---- sub_00275 ----
sub_00275:
  00275  b8d720         mov      ax, 0x20d7  ; 0000:0275
  00278  e9b4ff         jmp      sub_0022F  ; 0000:0278

; ---- sub_0027B ----
sub_0027B:
  0027B  b80721         mov      ax, 0x2107  ; 0000:027B
  0027E  e9aeff         jmp      sub_0022F  ; 0000:027E
  00281  50             push     ax  ; 0000:0281
  00282  b8d520         mov      ax, 0x20d5  ; 0000:0282
  00285  25ff0f         and      ax, 0xfff  ; 0000:0285
  00288  ff1e5c00       lcall    [0x5c]  ; 0000:0288
  0028C  c7066800ff0f   mov      word ptr [0x68], 0xfff  ; 0000:028C
  00292  3c20           cmp      al, 0x20  ; 0000:0292
  00294  7e10           jle      loc_002A6  ; 0000:0294
  00296  c7066800ffff   mov      word ptr [0x68], 0xffff  ; 0000:0296
  0029C  3c37           cmp      al, 0x37  ; 0000:029C
  0029E  7e06           jle      loc_002A6  ; 0000:029E
  002A0  c7066800ffef   mov      word ptr [0x68], 0xefff  ; 0000:02A0
loc_002A6:
  002A6  58             pop      ax  ; 0000:02A6
  002A7  cb             retf       ; 0000:02A7
  002A8  813e6800ff0f   cmp      word ptr [0x68], 0xfff  ; 0000:02A8
  002AE  7411           je       loc_002C1  ; 0000:02AE
  002B0  813e6800ffef   cmp      word ptr [0x68], 0xefff  ; 0000:02B0
  002B6  741e           je       loc_002D6  ; 0000:02B6
  002B8  3d4421         cmp      ax, 0x2144  ; 0000:02B8
  002BB  7e19           jle      loc_002D6  ; 0000:02BB
  002BD  b8ffff         mov      ax, 0xffff  ; 0000:02BD
  002C0  cb             retf       ; 0000:02C0
loc_002C1:
  002C1  3d0a21         cmp      ax, 0x210a  ; 0000:02C1
  002C4  7f05           jg       loc_002CB  ; 0000:02C4
  002C6  23066800       and      ax, word ptr [0x68]  ; 0000:02C6
  002CA  cb             retf       ; 0000:02CA
loc_002CB:
  002CB  3d2d21         cmp      ax, 0x212d  ; 0000:02CB
  002CE  b8feff         mov      ax, 0xfffe  ; 0000:02CE
  002D1  7403           je       loc_002D6  ; 0000:02D1
  002D3  b8ffff         mov      ax, 0xffff  ; 0000:02D3
loc_002D6:
  002D6  cb             retf       ; 0000:02D6
  002D7  9c             pushf      ; 0000:02D7
  002D8  3d9020         cmp      ax, 0x2090  ; 0000:02D8
  002DB  7522           jne      loc_002FF  ; 0000:02DB
  002DD  813e6800ff0f   cmp      word ptr [0x68], 0xfff  ; 0000:02DD
  002E3  741a           je       loc_002FF  ; 0000:02E3
  002E5  50             push     ax  ; 0000:02E5
  002E6  b8d520         mov      ax, 0x20d5  ; 0000:02E6
  002E9  ff1e5c00       lcall    [0x5c]  ; 0000:02E9
  002ED  3c29           cmp      al, 0x29  ; 0000:02ED
  002EF  58             pop      ax  ; 0000:02EF
  002F0  7f0d           jg       loc_002FF  ; 0000:02F0
  002F2  53             push     bx  ; 0000:02F2
  002F3  8b5d0e         mov      bx, word ptr [di + 0xe]  ; 0000:02F3
  002F6  8b1f           mov      bx, word ptr [bx]  ; 0000:02F6
  002F8  d1e3           shl      bx, 1  ; 0000:02F8
  002FA  43             inc      bx  ; 0000:02FA
  002FB  295d02         sub      word ptr [di + 2], bx  ; 0000:02FB
  002FE  5b             pop      bx  ; 0000:02FE
loc_002FF:
  002FF  9d             popf       ; 0000:02FF
  00300  cb             retf       ; 0000:0300
  00301  9c             pushf      ; 0000:0301
  00302  813e66009020   cmp      word ptr [0x66], 0x2090  ; 0000:0302
  00308  740a           je       loc_00314  ; 0000:0308
  0030A  813e66001721   cmp      word ptr [0x66], 0x2117  ; 0000:030A
  00310  7402           je       loc_00314  ; 0000:0310
  00312  9d             popf       ; 0000:0312
  00313  cb             retf       ; 0000:0313
loc_00314:
  00314  813e6800ff0f   cmp      word ptr [0x68], 0xfff  ; 0000:0314
  0031A  746a           je       loc_00386  ; 0000:031A
  0031C  50             push     ax  ; 0000:031C
  0031D  b8d520         mov      ax, 0x20d5  ; 0000:031D
  00320  ff1e5c00       lcall    [0x5c]  ; 0000:0320
  00324  3c29           cmp      al, 0x29  ; 0000:0324
  00326  7f18           jg       loc_00340  ; 0000:0326
  00328  813e66001721   cmp      word ptr [0x66], 0x2117  ; 0000:0328
  0032E  7410           je       loc_00340  ; 0000:032E
  00330  58             pop      ax  ; 0000:0330
  00331  53             push     bx  ; 0000:0331
  00332  8b5d0e         mov      bx, word ptr [di + 0xe]  ; 0000:0332
  00335  8b1f           mov      bx, word ptr [bx]  ; 0000:0335
  00337  d1e3           shl      bx, 1  ; 0000:0337
  00339  43             inc      bx  ; 0000:0339
  0033A  015d02         add      word ptr [di + 2], bx  ; 0000:033A
  0033D  5b             pop      bx  ; 0000:033D
  0033E  eb46           jmp      loc_00386  ; 0000:033E
loc_00340:
  00340  3c37           cmp      al, 0x37  ; 0000:0340
  00342  58             pop      ax  ; 0000:0342
  00343  7f41           jg       loc_00386  ; 0000:0343
  00345  813e66001721   cmp      word ptr [0x66], 0x2117  ; 0000:0345
  0034B  7539           jne      loc_00386  ; 0000:034B
  0034D  56             push     si  ; 0000:034D
  0034E  57             push     di  ; 0000:034E
  0034F  51             push     cx  ; 0000:034F
  00350  52             push     dx  ; 0000:0350
  00351  8b7600         mov      si, word ptr [bp]  ; 0000:0351
  00354  83c604         add      si, 4  ; 0000:0354
  00357  e82e00         call     sub_00388  ; 0000:0357
  0035A  32e4           xor      ah, ah  ; 0000:035A
  0035C  b104           mov      cl, 4  ; 0000:035C
  0035E  f6e1           mul      cl  ; 0000:035E
  00360  bf6a00         mov      di, 0x6a  ; 0000:0360
  00363  03f8           add      di, ax  ; 0000:0363
  00365  b90400         mov      cx, 4  ; 0000:0365
  00368  b80000         mov      ax, 0  ; 0000:0368
  0036B  4e             dec      si  ; 0000:036B
  0036C  4f             dec      di  ; 0000:036C
  0036D  47             inc      di  ; 0000:036D
  0036E  46             inc      si  ; 0000:036E
  0036F  8a15           mov      dl, byte ptr [di]  ; 0000:036F
  00371  0a14           or       dl, byte ptr [si]  ; 0000:0371
  00373  740d           je       loc_00382  ; 0000:0373
  00375  8a15           mov      dl, byte ptr [di]  ; 0000:0375
  00377  3814           cmp      byte ptr [si], dl  ; 0000:0377
  00379  7504           jne      loc_0037F  ; 0000:0379
  0037B  e2f0           loop     0x36d  ; 0000:037B
  0037D  eb03           jmp      loc_00382  ; 0000:037D
loc_0037F:
  0037F  b8ffff         mov      ax, 0xffff  ; 0000:037F
loc_00382:
  00382  5a             pop      dx  ; 0000:0382
  00383  59             pop      cx  ; 0000:0383
  00384  5f             pop      di  ; 0000:0384
  00385  5e             pop      si  ; 0000:0385
loc_00386:
  00386  9d             popf       ; 0000:0386
  00387  cb             retf       ; 0000:0387

; ---- sub_00388 ----
sub_00388:
  00388  55             push     bp  ; 0000:0388
  00389  83ec0b         sub      sp, 0xb  ; 0000:0389
  0038C  8bec           mov      bp, sp  ; 0000:038C
  0038E  1e             push     ds  ; 0000:038E
  0038F  1e             push     ds  ; 0000:038F
  00390  07             pop      es  ; 0000:0390
  00391  16             push     ss  ; 0000:0391
  00392  1f             pop      ds  ; 0000:0392
  00393  8d4600         lea      ax, [bp]  ; 0000:0393
  00396  55             push     bp  ; 0000:0396
  00397  50             push     ax  ; 0000:0397
  00398  8bec           mov      bp, sp  ; 0000:0398
  0039A  b83120         mov      ax, 0x2031  ; 0000:039A
  0039D  25ff0f         and      ax, 0xfff  ; 0000:039D
  003A0  26ff1e5c00     lcall    es:[0x5c]  ; 0000:03A0
  003A5  83c402         add      sp, 2  ; 0000:03A5
  003A8  5d             pop      bp  ; 0000:03A8
  003A9  1f             pop      ds  ; 0000:03A9
  003AA  8a4600         mov      al, byte ptr [bp]  ; 0000:03AA
  003AD  83c40b         add      sp, 0xb  ; 0000:03AD
  003B0  5d             pop      bp  ; 003B:0000
  003B1  c3             ret        ; 003B:0001

; ---- start ----
start:
  003B2  3031           xor      byte ptr [bx + di], dh  ; 003B:0002
  003B4  2e3032         xor      byte ptr cs:[bp + si], dh  ; 003B:0004
  003B7  0201           add      al, byte ptr [bx + di]  ; 003B:0007
  003B9  44             inc      sp  ; 003B:0009
  003BA  52             push     dx  ; 003B:000A
  003BB  57             push     di  ; 003B:000B
  003BC  50             push     ax  ; 003B:000C
  003BD  52             push     dx  ; 003B:000D
  003BE  54             push     sp  ; 003B:000E
  003BF  46             inc      si  ; 003B:000F
  003C0  49             dec      cx  ; 003B:0010
  003C1  4c             dec      sp  ; 003B:0011
  003C2  45             inc      bp  ; 003B:0012
  003C3  005052         add      byte ptr [bx + si + 0x52], dl  ; 003B:0013
  003C6  49             dec      cx  ; 003B:0016
  003C7  4e             dec      si  ; 003B:0017
  003C8  54             push     sp  ; 003B:0018
  003C9  5f             pop      di  ; 003B:0019
  003CA  49             dec      cx  ; 003B:001A
  003CB  4e             dec      si  ; 003B:001B
  003CC  46             inc      si  ; 003B:001C
  003CD  4f             dec      di  ; 003B:001D
  003CE  0000           add      byte ptr [bx + si], al  ; 003B:001E
  003D0  0000           add      byte ptr [bx + si], al  ; 003B:0020
  003D2  0000           add      byte ptr [bx + si], al  ; 003B:0022
  003D4  0000           add      byte ptr [bx + si], al  ; 003B:0024
  003D6  0000           add      byte ptr [bx + si], al  ; 003B:0026
  003D8  0000           add      byte ptr [bx + si], al  ; 003B:0028
  003DA  0000           add      byte ptr [bx + si], al  ; 003B:002A
  003DC  0000           add      byte ptr [bx + si], al  ; 003B:002C
  003DE  0000           add      byte ptr [bx + si], al  ; 003B:002E
  003E0  0000           add      byte ptr [bx + si], al  ; 003B:0030
  003E2  0000           add      byte ptr [bx + si], al  ; 003B:0032
  003E4  0000           add      byte ptr [bx + si], al  ; 003B:0034
  003E6  0000           add      byte ptr [bx + si], al  ; 003B:0036
  003E8  0000           add      byte ptr [bx + si], al  ; 003B:0038
  003EA  0000           add      byte ptr [bx + si], al  ; 003B:003A
  003EC  0000           add      byte ptr [bx + si], al  ; 003B:003C
  003EE  cdab           int      0xab  ; 003B:003E
  003F0  badc50         mov      dx, 0x50dc  ; 003B:0040
  003F3  52             push     dx  ; 003B:0043
  003F4  47             inc      di  ; 003B:0044
  003F5  55             push     bp  ; 003B:0045
  003F6  46             inc      si  ; 003B:0046
  003F7  00cd           add      ch, cl  ; 003B:0047
  003F9  ab             stosw    word ptr es:[di], ax  ; 003B:0049
  003FA  badc44         mov      dx, 0x44dc  ; 003B:004A
  003FD  4d             dec      bp  ; 003B:004D
  003FE  47             inc      di  ; 003B:004E
  003FF  55             push     bp  ; 003B:004F
  00400  46             inc      si  ; 003B:0050
  00401  0000           add      byte ptr [bx + si], al  ; 003B:0051
  00403  0000           add      byte ptr [bx + si], al  ; 003B:0053
  00405  53             push     bx  ; 003B:0055
  00406  0000           add      byte ptr [bx + si], al  ; 003B:0056
  00408  0000           add      byte ptr [bx + si], al  ; 003B:0058
  0040A  0000           add      byte ptr [bx + si], al  ; 003B:005A
  0040C  cdab           int      0xab  ; 003B:005C
  0040E  badc44         mov      dx, 0x44dc  ; 003B:005E
  00411  4d             dec      bp  ; 003B:0061
  00412  43             inc      bx  ; 003B:0062
  00413  53             push     bx  ; 003B:0063
  00414  52             push     dx  ; 003B:0064
  00415  0000           add      byte ptr [bx + si], al  ; 003B:0065
  00417  0000           add      byte ptr [bx + si], al  ; 003B:0067
  00419  0031           add      byte ptr [bx + di], dh  ; 003B:0069
  0041B  3030           xor      byte ptr [bx + si], dh  ; 003B:006B
  0041D  304347         xor      byte ptr [bp + di + 0x47], al  ; 003B:006D
  00420  41             inc      cx  ; 003B:0070
  00421  004444         add      byte ptr [si + 0x44], al  ; 003B:0071
  00424  47             inc      di  ; 003B:0074
  00425  41             inc      cx  ; 003B:0075
  00426  45             inc      bp  ; 003B:0076
  00427  47             inc      di  ; 003B:0077
  00428  41             inc      cx  ; 003B:0078
  00429  004845         add      byte ptr [bx + si + 0x45], cl  ; 003B:0079
  0042C  52             push     dx  ; 003B:007C
  0042D  43             inc      bx  ; 003B:007D
  0042E  50             push     ax  ; 003B:007E
  0042F  4c             dec      sp  ; 003B:007F
  00430  41             inc      cx  ; 003B:0080
  00431  4e             dec      si  ; 003B:0081
  00432  54             push     sp  ; 003B:0082
  00433  43             inc      bx  ; 003B:0083
  00434  31365443       xor      word ptr [0x4354], si  ; 003B:0084
  00438  3400           xor      al, 0  ; 003B:0088
  0043A  56             push     si  ; 003B:008A
  0043B  47             inc      di  ; 003B:008B
  0043C  41             inc      cx  ; 003B:008C
  0043D  004d43         add      byte ptr [di + 0x43], cl  ; 003B:008D
  00440  47             inc      di  ; 003B:0090
  00441  41             inc      cx  ; 003B:0091
  00442  45             inc      bp  ; 003B:0092
  00443  47             inc      di  ; 003B:0093
  00444  41             inc      cx  ; 003B:0094
  00445  004c52         add      byte ptr [si + 0x52], cl  ; 003B:0095
  00448  45             inc      bp  ; 003B:0098
  00449  53             push     bx  ; 003B:0099
  0044A  54             push     sp  ; 003B:009A
  0044B  3235           xor      dh, byte ptr [di]  ; 003B:009B
  0044D  3654           push     sp  ; 003B:009D
  0044F  43             inc      bx  ; 003B:009F
  00450  3430           xor      al, 0x30  ; 003B:00A0
  00452  48             dec      ax  ; 003B:00A2
  00453  0000           add      byte ptr [bx + si], al  ; 003B:00A3
  00455  004300         add      byte ptr [bp + di], al  ; 003B:00A5
  00458  0000           add      byte ptr [bx + si], al  ; 003B:00A8
  0045A  4d             dec      bp  ; 003B:00AA
  0045B  0000           add      byte ptr [bx + si], al  ; 003B:00AB
  0045D  004500         add      byte ptr [di], al  ; 003B:00AD
  00460  0000           add      byte ptr [bx + si], al  ; 003B:00B0
  00462  54             push     sp  ; 003B:00B2
  00463  0000           add      byte ptr [bx + si], al  ; 003B:00B3
  00465  00             db       0x00  ; 003B:00B5
