; ========================================================================
; Disassembly of /Users/joe/Documents/GitHub/bayside/archive/deskmate-3.05/extracted/AUTOLOAD.RES
; Generated by disasm_mz.py (Bayside project)
; ========================================================================

; MZ Header:
;   File size:        4244 bytes
;   Header size:      512 bytes
;   Code size:        3732 bytes
;   Pages:            9
;   Relocations:      8
;   Entry point:      0000:0027
;   Init SS:SP:       00F0:0002
;   Min alloc:        0x0000 paragraphs
;   Max alloc:        0x0001 paragraphs
;   DM89 signature:   present
;   DM89 raw:         444d38393e0f013e000000000000f100000000000000000000000000000000000000

; Segment Map:
;   seg_0000  file=0x0200  (CODE/DATA)
;   seg_00C1  file=0x0E10  (CODE/DATA)
;   seg_00F0  file=0x1100  (BSS)

; Relocation Table (8 entries):
;   00C1:00FB  file=0x0F0B  value=seg_0000
;   00C1:00FF  file=0x0F0F  value=seg_0000
;   0000:0028  file=0x0228  value=seg_00C1
;   0000:004A  file=0x024A  value=seg_0000
;   0000:0A84  file=0x0C84  value=seg_0000
;   0000:0AB0  file=0x0CB0  value=seg_0000
;   0000:0ABF  file=0x0CBF  value=seg_0000
;   0000:0ACB  file=0x0CCB  value=seg_0000

; String Table:
;   0000:0B18 (0x0D18): "=D!~"
;   0000:0B9F (0x0D9F): "F<7X"
;   0000:0BAA (0x0DAA): "!u9VWQR"
;   0000:0BCB (0x0DCB): "NOGF"
;   0000:0BE2 (0x0DE2): "ZY_^"
;   00C1:0002 (0x0E12): "Create Startup"
;   00C1:0011 (0x0E21): "To prevent an additional disk swap, we need to write a file on t..."
;   00C1:006B (0x0E7B): "Please insert the disk containing DESK.EXE into drive X:"
;   00C1:00A4 (0x0EB4): "Insert the disk you wish to have startup information stored on i..."
;   00C1:00F1 (0x0F01): "AUTOLOADi"
;   00C1:01D8 (0x0FE8): "X:\AUTOLOAD.CFG"
;   00C1:01E8 (0x0FF8): "COMSPEC="
;   00C1:01F1 (0x1001): "X:\DESK.EXE"
;   00C1:0202 (0x1012): "PRGUF"
;   00C1:020C (0x101C): "DMGUF"
;   00C1:0224 (0x1034): "PRGUF"
;   00C1:022E (0x103E): "DMCSR"
;   00C1:0238 (0x1048): "1000CGA"
;   00C1:0240 (0x1050): "DDGAEGA"
;   00C1:0248 (0x1058): "HERCPLANTC16TC4"
;   00C1:025C (0x106C): "MCGAEGA"
;   00C1:0264 (0x1074): "LREST256TC40H"

; Analysis Summary:
;   Instructions:     1118
;   Functions (CALL): 49
;   Jump targets:     105
;   Strings:          22
;   INT calls:        25

; ========================================================================
; CODE / DATA
; ========================================================================

; ------------------------------------------------------------------------
; SEGMENT seg_0000  (3088 bytes, file 0x0200-0x0E10)
; ------------------------------------------------------------------------
seg_0000:


sub_0000_0000:
  0000:0000  e86e0a            call     0xa71  ; -> sub_0000_0A71
  0000:0003  3dffff            cmp      ax, 0xffff
  0000:0006  7415              je       0x1d  ; -> loc_0000_001D
  0000:0008  e81b08            call     0x826  ; -> sub_0000_0826
  0000:000B  3dffff            cmp      ax, 0xffff
  0000:000E  7407              je       0x17  ; -> loc_0000_0017
  0000:0010  33c0              xor      ax, ax
  0000:0012  eb09              jmp      0x1d  ; -> loc_0000_001D
  0000:0014  db E8 51 08                                        ; |.Q.|

loc_0000_0017:
  0000:0017  e8700a            call     0xa8a  ; -> sub_0000_0A8A
  0000:001A  b8ffff            mov      ax, 0xffff

loc_0000_001D:
  0000:001D  c3                ret      
  0000:001E  db E8 47 08 E8 66 0A C3 00 00                      ; |.G..f....|

entry_point:
  0000:0027  b8c100            mov      ax, 0xc1  ; RELOC->seg_00C1
  0000:002A  8ed8              mov      ds, ax
  0000:002C  2e8c1e2500        mov      word ptr cs:[0x25], ds
  0000:0031  e82b0a            call     0xa5f  ; -> sub_0000_0A5F
  0000:0034  250080            and      ax, 0x8000
  0000:0037  7405              je       0x3e  ; -> loc_0000_003E
  0000:0039  b8f001            mov      ax, 0x1f0
  0000:003C  eb03              jmp      0x41  ; -> loc_0000_0041

loc_0000_003E:
  0000:003E  b8ff01            mov      ax, 0x1ff

loc_0000_0041:
  0000:0041  bbf100            mov      bx, 0xf1
  0000:0044  8c4720            mov      word ptr [bx + 0x20], es
  0000:0047  1e                push     ds
  0000:0048  07                pop      es
  0000:0049  b90000            mov      cx, 0  ; RELOC->seg_0000
  0000:004C  cde0              int      0xe0  ; INT E0h, AH=01h
  0000:004E  e8afff            call     0  ; -> sub_0000_0000
  0000:0051  a2f000            mov      byte ptr [0xf0], al
  0000:0054  a11101            mov      ax, word ptr [0x111]
  0000:0057  8ec0              mov      es, ax
  0000:0059  268b1e0200        mov      bx, word ptr es:[2]
  0000:005E  2bd8              sub      bx, ax
  0000:0060  8bd3              mov      dx, bx
  0000:0062  a0f000            mov      al, byte ptr [0xf0]
  0000:0065  b431              mov      ah, 0x31
  0000:0067  cd21              int      0x21  ; INT 21h/31h: TSR (keep process)
  0000:0069  55                push     bp
  0000:006A  06                push     es
  0000:006B  1e                push     ds
  0000:006C  56                push     si
  0000:006D  8bec              mov      bp, sp
  0000:006F  4c                dec      sp
  0000:0070  1e                push     ds
  0000:0071  07                pop      es
  0000:0072  2e8e1e2500        mov      ds, word ptr cs:[0x25]
  0000:0077  e81900            call     0x93  ; -> sub_0000_0093
  0000:007A  8be5              mov      sp, bp
  0000:007C  5e                pop      si
  0000:007D  1f                pop      ds
  0000:007E  07                pop      es
  0000:007F  5d                pop      bp
  0000:0080  cb                retf     
  0000:0081  db 1E 2E 8E 1E 25 00 80 3E F0 00 00 75 03 E8 8D FF ; |....%..>...u....|
  0000:0091  db 1F CB                                           ; |..|

sub_0000_0093:
  0000:0093  53                push     bx
  0000:0094  51                push     cx
  0000:0095  52                push     dx
  0000:0096  57                push     di
  0000:0097  56                push     si
  0000:0098  06                push     es
  0000:0099  368b37            mov      si, word ptr ss:[bx]
  0000:009C  bfc601            mov      di, 0x1c6
  0000:009F  1e                push     ds
  0000:00A0  06                push     es
  0000:00A1  1f                pop      ds
  0000:00A2  07                pop      es
  0000:00A3  b91100            mov      cx, 0x11
  0000:00A6  f3a4              rep movsb byte ptr es:[di], byte ptr [si]
  0000:00A8  06                push     es
  0000:00A9  1f                pop      ds
  0000:00AA  803ed10103        cmp      byte ptr [0x1d1], 3
  0000:00AF  750f              jne      0xc0  ; -> loc_0000_00C0
  0000:00B1  c706de020040      mov      word ptr [0x2de], 0x4000
  0000:00B7  c706dc02ffbf      mov      word ptr [0x2dc], 0xbfff
  0000:00BD  eb0d              jmp      0xcc  ; -> loc_0000_00CC
  0000:00BF  db 90                                              ; |.|

loc_0000_00C0:
  0000:00C0  c706de020080      mov      word ptr [0x2de], 0x8000
  0000:00C6  c706dc02ff7f      mov      word ptr [0x2dc], 0x7fff

loc_0000_00CC:
  0000:00CC  c606d70100        mov      byte ptr [0x1d7], 0
  0000:00D1  803ed10101        cmp      byte ptr [0x1d1], 1
  0000:00D6  7c10              jl       0xe8  ; -> loc_0000_00E8
  0000:00D8  e85605            call     0x631  ; -> sub_0000_0631
  0000:00DB  3dffff            cmp      ax, 0xffff
  0000:00DE  7503              jne      0xe3  ; -> loc_0000_00E3
  0000:00E0  e93d01            jmp      0x220  ; -> loc_0000_0220

loc_0000_00E3:
  0000:00E3  c606d70101        mov      byte ptr [0x1d7], 1

loc_0000_00E8:
  0000:00E8  c606e90200        mov      byte ptr [0x2e9], 0
  0000:00ED  e87a05            call     0x66a  ; -> sub_0000_066A
  0000:00F0  730d              jae      0xff  ; -> loc_0000_00FF
  0000:00F2  e82702            call     0x31c  ; -> sub_0000_031C
  0000:00F5  3dffff            cmp      ax, 0xffff
  0000:00F8  7f2d              jg       0x127  ; -> loc_0000_0127
  0000:00FA  7c03              jl       0xff  ; -> loc_0000_00FF
  0000:00FC  e90f01            jmp      0x20e  ; -> loc_0000_020E

loc_0000_00FF:
  0000:00FF  803ed10100        cmp      byte ptr [0x1d1], 0
  0000:0104  7510              jne      0x116  ; -> loc_0000_0116
  0000:0106  33c0              xor      ax, ax
  0000:0108  8b16d802          mov      dx, word ptr [0x2d8]
  0000:010C  2316dc02          and      dx, word ptr [0x2dc]
  0000:0110  e80106            call     0x714  ; -> sub_0000_0714
  0000:0113  e9f800            jmp      0x20e  ; -> loc_0000_020E

loc_0000_0116:
  0000:0116  c706da020000      mov      word ptr [0x2da], 0
  0000:011C  e8e702            call     0x406  ; -> sub_0000_0406
  0000:011F  3dffff            cmp      ax, 0xffff
  0000:0122  7f55              jg       0x179  ; -> loc_0000_0179
  0000:0124  e9e700            jmp      0x20e  ; -> loc_0000_020E

loc_0000_0127:
  0000:0127  e86e03            call     0x498  ; -> sub_0000_0498
  0000:012A  3dffff            cmp      ax, 0xffff
  0000:012D  7503              jne      0x132  ; -> loc_0000_0132
  0000:012F  e9dc00            jmp      0x20e  ; -> loc_0000_020E

loc_0000_0132:
  0000:0132  803ed10100        cmp      byte ptr [0x1d1], 0
  0000:0137  7503              jne      0x13c  ; -> loc_0000_013C
  0000:0139  e99d00            jmp      0x1d9  ; -> loc_0000_01D9

loc_0000_013C:
  0000:013C  e8fe05            call     0x73d  ; -> sub_0000_073D
  0000:013F  3dffff            cmp      ax, 0xffff
  0000:0142  7425              je       0x169  ; -> loc_0000_0169
  0000:0144  50                push     ax
  0000:0145  e80705            call     0x64f  ; -> sub_0000_064F
  0000:0148  c606d70100        mov      byte ptr [0x1d7], 0
  0000:014D  58                pop      ax
  0000:014E  48                dec      ax
  0000:014F  bb1100            mov      bx, 0x11
  0000:0152  f7eb              imul     bx
  0000:0154  8bd8              mov      bx, ax
  0000:0156  81c31c01          add      bx, 0x11c
  0000:015A  8a0ed101          mov      cl, byte ptr [0x1d1]
  0000:015E  384f0b            cmp      byte ptr [bx + 0xb], cl
  0000:0161  7469              je       0x1cc  ; -> loc_0000_01CC
  0000:0163  884f0b            mov      byte ptr [bx + 0xb], cl
  0000:0166  eb2c              jmp      0x194  ; -> loc_0000_0194
  0000:0168  db 90                                              ; |.|

loc_0000_0169:
  0000:0169  833eda020a        cmp      word ptr [0x2da], 0xa
  0000:016E  7509              jne      0x179  ; -> loc_0000_0179
  0000:0170  e8f303            call     0x566  ; -> sub_0000_0566
  0000:0173  b8ffff            mov      ax, 0xffff
  0000:0176  e99500            jmp      0x20e  ; -> loc_0000_020E

loc_0000_0179:
  0000:0179  8b0eda02          mov      cx, word ptr [0x2da]
  0000:017D  b81100            mov      ax, 0x11
  0000:0180  f7e9              imul     cx
  0000:0182  8bf8              mov      di, ax
  0000:0184  81c71c01          add      di, 0x11c
  0000:0188  bec601            mov      si, 0x1c6
  0000:018B  b91100            mov      cx, 0x11
  0000:018E  f3a4              rep movsb byte ptr es:[di], byte ptr [si]
  0000:0190  ff06da02          inc      word ptr [0x2da]

loc_0000_0194:
  0000:0194  803ed10103        cmp      byte ptr [0x1d1], 3
  0000:0199  7512              jne      0x1ad  ; -> loc_0000_01AD
  0000:019B  a1da02            mov      ax, word ptr [0x2da]
  0000:019E  48                dec      ax
  0000:019F  b91100            mov      cx, 0x11
  0000:01A2  f7e9              imul     cx
  0000:01A4  051c01            add      ax, 0x11c
  0000:01A7  8bd8              mov      bx, ax
  0000:01A9  c6470b02          mov      byte ptr [bx + 0xb], 2

loc_0000_01AD:
  0000:01AD  be1c01            mov      si, 0x11c
  0000:01B0  8b0eda02          mov      cx, word ptr [0x2da]
  0000:01B4  b89000            mov      ax, 0x90
  0000:01B7  cde0              int      0xe0  ; INT E0h, AH=00h
  0000:01B9  803ed10103        cmp      byte ptr [0x1d1], 3
  0000:01BE  7504              jne      0x1c4  ; -> loc_0000_01C4
  0000:01C0  c6470b03          mov      byte ptr [bx + 0xb], 3

loc_0000_01C4:
  0000:01C4  e81903            call     0x4e0  ; -> sub_0000_04E0
  0000:01C7  3dffff            cmp      ax, 0xffff
  0000:01CA  740a              je       0x1d6  ; -> loc_0000_01D6

loc_0000_01CC:
  0000:01CC  e89703            call     0x566  ; -> sub_0000_0566
  0000:01CF  3dffff            cmp      ax, 0xffff
  0000:01D2  7402              je       0x1d6  ; -> loc_0000_01D6
  0000:01D4  33c0              xor      ax, ax

loc_0000_01D6:
  0000:01D6  eb36              jmp      0x20e  ; -> loc_0000_020E
  0000:01D8  db 90                                              ; |.|

loc_0000_01D9:
  0000:01D9  e86105            call     0x73d  ; -> sub_0000_073D
  0000:01DC  3dffff            cmp      ax, 0xffff
  0000:01DF  7502              jne      0x1e3  ; -> loc_0000_01E3
  0000:01E1  ebe9              jmp      0x1cc  ; -> loc_0000_01CC

loc_0000_01E3:
  0000:01E3  50                push     ax
  0000:01E4  b91100            mov      cx, 0x11
  0000:01E7  f7e9              imul     cx
  0000:01E9  8bf0              mov      si, ax
  0000:01EB  81c61c01          add      si, 0x11c
  0000:01EF  8bfe              mov      di, si
  0000:01F1  83ef11            sub      di, 0x11
  0000:01F4  58                pop      ax
  0000:01F5  8bc8              mov      cx, ax
  0000:01F7  a1da02            mov      ax, word ptr [0x2da]
  0000:01FA  2bc1              sub      ax, cx
  0000:01FC  b91100            mov      cx, 0x11
  0000:01FF  f7e9              imul     cx
  0000:0201  8bc8              mov      cx, ax
  0000:0203  f3a4              rep movsb byte ptr es:[di], byte ptr [si]
  0000:0205  e84704            call     0x64f  ; -> sub_0000_064F
  0000:0208  ff0eda02          dec      word ptr [0x2da]
  0000:020C  eb86              jmp      0x194  ; -> loc_0000_0194

loc_0000_020E:
  0000:020E  3dffff            cmp      ax, 0xffff
  0000:0211  750d              jne      0x220  ; -> loc_0000_0220
  0000:0213  803ed70101        cmp      byte ptr [0x1d7], 1
  0000:0218  7506              jne      0x220  ; -> loc_0000_0220
  0000:021A  e83204            call     0x64f  ; -> sub_0000_064F
  0000:021D  b8ffff            mov      ax, 0xffff

loc_0000_0220:
  0000:0220  07                pop      es
  0000:0221  5e                pop      si
  0000:0222  5f                pop      di
  0000:0223  5a                pop      dx
  0000:0224  59                pop      cx
  0000:0225  5b                pop      bx
  0000:0226  c3                ret      

sub_0000_0227:
  0000:0227  50                push     ax
  0000:0228  57                push     di
  0000:0229  56                push     si
  0000:022A  bf8402            mov      di, 0x284
  0000:022D  57                push     di
  0000:022E  e83408            call     0xa65  ; -> sub_0000_0A65
  0000:0231  83c402            add      sp, 2
  0000:0234  a3e002            mov      word ptr [0x2e0], ax
  0000:0237  e84705            call     0x781  ; -> sub_0000_0781
  0000:023A  03f8              add      di, ax
  0000:023C  4f                dec      di
  0000:023D  803d5c            cmp      byte ptr [di], 0x5c
  0000:0240  7404              je       0x246  ; -> loc_0000_0246
  0000:0242  47                inc      di
  0000:0243  c6055c            mov      byte ptr [di], 0x5c

loc_0000_0246:
  0000:0246  47                inc      di
  0000:0247  bedb01            mov      si, 0x1db
  0000:024A  e84f05            call     0x79c  ; -> sub_0000_079C
  0000:024D  5e                pop      si
  0000:024E  5f                pop      di
  0000:024F  58                pop      ax
  0000:0250  c3                ret      

sub_0000_0251:
  0000:0251  50                push     ax
  0000:0252  53                push     bx
  0000:0253  51                push     cx
  0000:0254  57                push     di
  0000:0255  56                push     si
  0000:0256  06                push     es
  0000:0257  b451              mov      ah, 0x51
  0000:0259  cd21              int      0x21  ; INT 21h/51h: Get PSP
  0000:025B  8ec3              mov      es, bx
  0000:025D  268e062c00        mov      es, word ptr es:[0x2c]
  0000:0262  33ff              xor      di, di

loc_0000_0264:
  0000:0264  26833d00          cmp      word ptr es:[di], 0
  0000:0268  7403              je       0x26d  ; -> loc_0000_026D
  0000:026A  47                inc      di
  0000:026B  ebf7              jmp      0x264  ; -> loc_0000_0264

loc_0000_026D:
  0000:026D  47                inc      di
  0000:026E  8bcf              mov      cx, di
  0000:0270  33ff              xor      di, di

loc_0000_0272:
  0000:0272  bee801            mov      si, 0x1e8
  0000:0275  8a04              mov      al, byte ptr [si]
  0000:0277  f2ae              repne scasb al, byte ptr es:[di]
  0000:0279  7533              jne      0x2ae  ; -> loc_0000_02AE
  0000:027B  51                push     cx
  0000:027C  57                push     di
  0000:027D  4f                dec      di
  0000:027E  b90800            mov      cx, 8
  0000:0281  f3a6              repe cmpsb byte ptr [si], byte ptr es:[di]
  0000:0283  5f                pop      di
  0000:0284  59                pop      cx
  0000:0285  75eb              jne      0x272  ; -> loc_0000_0272
  0000:0287  83c707            add      di, 7
  0000:028A  26807d013a        cmp      byte ptr es:[di + 1], 0x3a
  0000:028F  751d              jne      0x2ae  ; -> loc_0000_02AE
  0000:0291  268a05            mov      al, byte ptr es:[di]
  0000:0294  3c5a              cmp      al, 0x5a
  0000:0296  7e02              jle      0x29a  ; -> loc_0000_029A
  0000:0298  2c20              sub      al, 0x20

loc_0000_029A:
  0000:029A  b97000            mov      cx, 0x70
  0000:029D  8ec1              mov      es, cx
  0000:029F  268a1e0000        mov      bl, byte ptr es:[0]
  0000:02A4  80c340            add      bl, 0x40
  0000:02A7  3ac3              cmp      al, bl
  0000:02A9  7403              je       0x2ae  ; -> loc_0000_02AE
  0000:02AB  eb03              jmp      0x2b0  ; -> loc_0000_02B0
  0000:02AD  db 90                                              ; |.|

loc_0000_02AE:
  0000:02AE  b041              mov      al, 0x41

loc_0000_02B0:
  0000:02B0  a2f101            mov      byte ptr [0x1f1], al
  0000:02B3  a2d801            mov      byte ptr [0x1d8], al
  0000:02B6  bed801            mov      si, 0x1d8
  0000:02B9  bf8402            mov      di, 0x284
  0000:02BC  e8dd04            call     0x79c  ; -> sub_0000_079C
  0000:02BF  07                pop      es
  0000:02C0  5e                pop      si
  0000:02C1  5f                pop      di
  0000:02C2  59                pop      cx
  0000:02C3  5b                pop      bx
  0000:02C4  58                pop      ax
  0000:02C5  c3                ret      

sub_0000_02C6:
  0000:02C6  b81100            mov      ax, 0x11
  0000:02C9  a31901            mov      word ptr [0x119], ax
  0000:02CC  c606160100        mov      byte ptr [0x116], 0
  0000:02D1  b81601            mov      ax, 0x116
  0000:02D4  50                push     ax
  0000:02D5  e80308            call     0xadb  ; -> sub_0000_0ADB
  0000:02D8  83c402            add      sp, 2
  0000:02DB  c606160101        mov      byte ptr [0x116], 1
  0000:02E0  e86eff            call     0x251  ; -> sub_0000_0251
  0000:02E3  eb28              jmp      0x30d  ; -> loc_0000_030D
  0000:02E5  db 90                                              ; |.|

loc_0000_02E6:
  0000:02E6  a0f101            mov      al, byte ptr [0x1f1]
  0000:02E9  3c5a              cmp      al, 0x5a
  0000:02EB  7e02              jle      0x2ef  ; -> loc_0000_02EF
  0000:02ED  2c20              sub      al, 0x20

loc_0000_02EF:
  0000:02EF  a2a100            mov      byte ptr [0xa1], al
  0000:02F2  b86b00            mov      ax, 0x6b
  0000:02F5  a31901            mov      word ptr [0x119], ax
  0000:02F8  b81601            mov      ax, 0x116
  0000:02FB  50                push     ax
  0000:02FC  e8dc07            call     0xadb  ; -> sub_0000_0ADB
  0000:02FF  83c402            add      sp, 2
  0000:0302  3d01f7            cmp      ax, 0xf701
  0000:0305  7406              je       0x30d  ; -> loc_0000_030D
  0000:0307  b8ffff            mov      ax, 0xffff
  0000:030A  eb0f              jmp      0x31b  ; -> loc_0000_031B
  0000:030C  db 90                                              ; |.|

loc_0000_030D:
  0000:030D  b8f101            mov      ax, 0x1f1
  0000:0310  50                push     ax
  0000:0311  e85707            call     0xa6b  ; -> sub_0000_0A6B
  0000:0314  83c402            add      sp, 2
  0000:0317  0bc0              or       ax, ax
  0000:0319  74cb              je       0x2e6  ; -> loc_0000_02E6

loc_0000_031B:
  0000:031B  c3                ret      

sub_0000_031C:
  0000:031C  52                push     dx
  0000:031D  e807ff            call     0x227  ; -> sub_0000_0227
  0000:0320  b88402            mov      ax, 0x284
  0000:0323  50                push     ax
  0000:0324  e84407            call     0xa6b  ; -> sub_0000_0A6B
  0000:0327  83c402            add      sp, 2
  0000:032A  0bc0              or       ax, ax
  0000:032C  7403              je       0x331  ; -> loc_0000_0331
  0000:032E  e99d00            jmp      0x3ce  ; -> loc_0000_03CE

loc_0000_0331:
  0000:0331  a08402            mov      al, byte ptr [0x284]
  0000:0334  3c5a              cmp      al, 0x5a
  0000:0336  7e02              jle      0x33a  ; -> loc_0000_033A
  0000:0338  2c20              sub      al, 0x20

loc_0000_033A:
  0000:033A  32e4              xor      ah, ah
  0000:033C  50                push     ax
  0000:033D  e82b06            call     0x96b  ; -> sub_0000_096B
  0000:0340  83c402            add      sp, 2
  0000:0343  0bc0              or       ax, ax
  0000:0345  7470              je       0x3b7  ; -> loc_0000_03B7
  0000:0347  803e1b0101        cmp      byte ptr [0x11b], 1
  0000:034C  7454              je       0x3a2  ; -> loc_0000_03A2
  0000:034E  c606e90201        mov      byte ptr [0x2e9], 1
  0000:0353  e87102            call     0x5c7  ; -> sub_0000_05C7
  0000:0356  7312              jae      0x36a  ; -> loc_0000_036A
  0000:0358  833ee00202        cmp      word ptr [0x2e0], 2
  0000:035D  750b              jne      0x36a  ; -> loc_0000_036A
  0000:035F  e864ff            call     0x2c6  ; -> sub_0000_02C6
  0000:0362  3dffff            cmp      ax, 0xffff
  0000:0365  752a              jne      0x391  ; -> loc_0000_0391
  0000:0367  e99a00            jmp      0x404  ; -> loc_0000_0404

loc_0000_036A:
  0000:036A  a08402            mov      al, byte ptr [0x284]
  0000:036D  3c5a              cmp      al, 0x5a
  0000:036F  7e02              jle      0x373  ; -> loc_0000_0373
  0000:0371  2c20              sub      al, 0x20

loc_0000_0373:
  0000:0373  a2ec00            mov      byte ptr [0xec], al
  0000:0376  b8a400            mov      ax, 0xa4
  0000:0379  a31901            mov      word ptr [0x119], ax
  0000:037C  b81601            mov      ax, 0x116
  0000:037F  50                push     ax
  0000:0380  e85807            call     0xadb  ; -> sub_0000_0ADB
  0000:0383  83c402            add      sp, 2
  0000:0386  3d01f7            cmp      ax, 0xf701
  0000:0389  7406              je       0x391  ; -> loc_0000_0391
  0000:038B  b8ffff            mov      ax, 0xffff
  0000:038E  eb74              jmp      0x404  ; -> loc_0000_0404
  0000:0390  db 90                                              ; |.|

loc_0000_0391:
  0000:0391  b88402            mov      ax, 0x284
  0000:0394  50                push     ax
  0000:0395  e8d306            call     0xa6b  ; -> sub_0000_0A6B
  0000:0398  83c402            add      sp, 2
  0000:039B  0bc0              or       ax, ax
  0000:039D  7418              je       0x3b7  ; -> loc_0000_03B7
  0000:039F  eb2d              jmp      0x3ce  ; -> loc_0000_03CE
  0000:03A1  db 90                                              ; |.|

loc_0000_03A2:
  0000:03A2  b88402            mov      ax, 0x284
  0000:03A5  50                push     ax
  0000:03A6  b8db01            mov      ax, 0x1db
  0000:03A9  50                push     ax
  0000:03AA  e8c405            call     0x971  ; -> sub_0000_0971
  0000:03AD  83c404            add      sp, 4
  0000:03B0  0bc0              or       ax, ax
  0000:03B2  7403              je       0x3b7  ; -> loc_0000_03B7
  0000:03B4  eb18              jmp      0x3ce  ; -> loc_0000_03CE
  0000:03B6  db 90                                              ; |.|

loc_0000_03B7:
  0000:03B7  8b16d802          mov      dx, word ptr [0x2d8]
  0000:03BB  2316dc02          and      dx, word ptr [0x2dc]
  0000:03BF  e85203            call     0x714  ; -> sub_0000_0714
  0000:03C2  b8feff            mov      ax, 0xfffe
  0000:03C5  c706da020000      mov      word ptr [0x2da], 0
  0000:03CB  eb37              jmp      0x404  ; -> loc_0000_0404
  0000:03CD  db 90                                              ; |.|

loc_0000_03CE:
  0000:03CE  b80200            mov      ax, 2
  0000:03D1  50                push     ax
  0000:03D2  b88402            mov      ax, 0x284
  0000:03D5  50                push     ax
  0000:03D6  e84a05            call     0x923  ; -> sub_0000_0923
  0000:03D9  83c404            add      sp, 4
  0000:03DC  3dffff            cmp      ax, 0xffff
  0000:03DF  7520              jne      0x401  ; -> loc_0000_0401
  0000:03E1  8b16d802          mov      dx, word ptr [0x2d8]
  0000:03E5  2316dc02          and      dx, word ptr [0x2dc]
  0000:03E9  e82803            call     0x714  ; -> sub_0000_0714
  0000:03EC  833e1302ff        cmp      word ptr [0x213], -1
  0000:03F1  7f06              jg       0x3f9  ; -> loc_0000_03F9
  0000:03F3  e8ac01            call     0x5a2  ; -> sub_0000_05A2
  0000:03F6  eb0c              jmp      0x404  ; -> loc_0000_0404
  0000:03F8  db 90                                              ; |.|

loc_0000_03F9:
  0000:03F9  50                push     ax
  0000:03FA  e84a05            call     0x947  ; -> sub_0000_0947
  0000:03FD  58                pop      ax
  0000:03FE  eb04              jmp      0x404  ; -> loc_0000_0404
  0000:0400  db 90                                              ; |.|

loc_0000_0401:
  0000:0401  a3e202            mov      word ptr [0x2e2], ax

loc_0000_0404:
  0000:0404  5a                pop      dx
  0000:0405  c3                ret      

sub_0000_0406:
  0000:0406  57                push     di
  0000:0407  52                push     dx
  0000:0408  e81cfe            call     0x227  ; -> sub_0000_0227
  0000:040B  a08402            mov      al, byte ptr [0x284]
  0000:040E  3c5a              cmp      al, 0x5a
  0000:0410  7e02              jle      0x414  ; -> loc_0000_0414
  0000:0412  2c20              sub      al, 0x20

loc_0000_0414:
  0000:0414  32e4              xor      ah, ah
  0000:0416  50                push     ax
  0000:0417  e85105            call     0x96b  ; -> sub_0000_096B
  0000:041A  83c402            add      sp, 2
  0000:041D  0bc0              or       ax, ax
  0000:041F  7503              jne      0x424  ; -> loc_0000_0424
  0000:0421  eb4d              jmp      0x470  ; -> loc_0000_0470
  0000:0423  db 90                                              ; |.|

loc_0000_0424:
  0000:0424  803ee90201        cmp      byte ptr [0x2e9], 1
  0000:0429  7445              je       0x470  ; -> loc_0000_0470
  0000:042B  803e1b0101        cmp      byte ptr [0x11b], 1
  0000:0430  7417              je       0x449  ; -> loc_0000_0449
  0000:0432  e89201            call     0x5c7  ; -> sub_0000_05C7
  0000:0435  7312              jae      0x449  ; -> loc_0000_0449
  0000:0437  833ee00202        cmp      word ptr [0x2e0], 2
  0000:043C  750b              jne      0x449  ; -> loc_0000_0449
  0000:043E  e885fe            call     0x2c6  ; -> sub_0000_02C6
  0000:0441  3dffff            cmp      ax, 0xffff
  0000:0444  752a              jne      0x470  ; -> loc_0000_0470
  0000:0446  eb4d              jmp      0x495  ; -> loc_0000_0495
  0000:0448  db 90                                              ; |.|

loc_0000_0449:
  0000:0449  a08402            mov      al, byte ptr [0x284]
  0000:044C  3c5a              cmp      al, 0x5a
  0000:044E  7e02              jle      0x452  ; -> loc_0000_0452
  0000:0450  2c20              sub      al, 0x20

loc_0000_0452:
  0000:0452  a2ec00            mov      byte ptr [0xec], al
  0000:0455  b8a400            mov      ax, 0xa4
  0000:0458  a31901            mov      word ptr [0x119], ax
  0000:045B  b81601            mov      ax, 0x116
  0000:045E  50                push     ax
  0000:045F  e87906            call     0xadb  ; -> sub_0000_0ADB
  0000:0462  83c402            add      sp, 2
  0000:0465  3d01f7            cmp      ax, 0xf701
  0000:0468  7406              je       0x470  ; -> loc_0000_0470
  0000:046A  b8ffff            mov      ax, 0xffff
  0000:046D  eb26              jmp      0x495  ; -> loc_0000_0495
  0000:046F  db 90                                              ; |.|

loc_0000_0470:
  0000:0470  bf8402            mov      di, 0x284
  0000:0473  57                push     di
  0000:0474  e8a004            call     0x917  ; -> sub_0000_0917
  0000:0477  83c402            add      sp, 2
  0000:047A  3dffff            cmp      ax, 0xffff
  0000:047D  7513              jne      0x492  ; -> loc_0000_0492
  0000:047F  8b16d802          mov      dx, word ptr [0x2d8]
  0000:0483  2316dc02          and      dx, word ptr [0x2dc]
  0000:0487  e88a02            call     0x714  ; -> sub_0000_0714
  0000:048A  50                push     ax
  0000:048B  e8bf04            call     0x94d  ; -> sub_0000_094D
  0000:048E  58                pop      ax
  0000:048F  eb04              jmp      0x495  ; -> loc_0000_0495
  0000:0491  db 90                                              ; |.|

loc_0000_0492:
  0000:0492  a3e202            mov      word ptr [0x2e2], ax

loc_0000_0495:
  0000:0495  5a                pop      dx
  0000:0496  5f                pop      di
  0000:0497  c3                ret      

sub_0000_0498:
  0000:0498  53                push     bx
  0000:0499  52                push     dx
  0000:049A  b8aa00            mov      ax, 0xaa
  0000:049D  50                push     ax
  0000:049E  b81c01            mov      ax, 0x11c
  0000:04A1  50                push     ax
  0000:04A2  a1e202            mov      ax, word ptr [0x2e2]
  0000:04A5  50                push     ax
  0000:04A6  e88004            call     0x929  ; -> sub_0000_0929
  0000:04A9  83c406            add      sp, 6
  0000:04AC  3dffff            cmp      ax, 0xffff
  0000:04AF  7523              jne      0x4d4  ; -> loc_0000_04D4
  0000:04B1  8b16d802          mov      dx, word ptr [0x2d8]
  0000:04B5  2316dc02          and      dx, word ptr [0x2dc]
  0000:04B9  e85802            call     0x714  ; -> sub_0000_0714
  0000:04BC  833e1302ff        cmp      word ptr [0x213], -1
  0000:04C1  7f06              jg       0x4c9  ; -> loc_0000_04C9
  0000:04C3  e8dc00            call     0x5a2  ; -> sub_0000_05A2
  0000:04C6  eb15              jmp      0x4dd  ; -> loc_0000_04DD
  0000:04C8  db 90                                              ; |.|

loc_0000_04C9:
  0000:04C9  50                push     ax
  0000:04CA  e88604            call     0x953  ; -> sub_0000_0953
  0000:04CD  e89600            call     0x566  ; -> sub_0000_0566
  0000:04D0  58                pop      ax
  0000:04D1  eb0a              jmp      0x4dd  ; -> loc_0000_04DD
  0000:04D3  db 90                                              ; |.|

loc_0000_04D4:
  0000:04D4  99                cdq      
  0000:04D5  bb1100            mov      bx, 0x11
  0000:04D8  f7fb              idiv     bx
  0000:04DA  a3da02            mov      word ptr [0x2da], ax

loc_0000_04DD:
  0000:04DD  5a                pop      dx
  0000:04DE  5b                pop      bx
  0000:04DF  c3                ret      

sub_0000_04E0:
  0000:04E0  53                push     bx
  0000:04E1  52                push     dx
  0000:04E2  33c0              xor      ax, ax
  0000:04E4  50                push     ax
  0000:04E5  50                push     ax
  0000:04E6  50                push     ax
  0000:04E7  a1e202            mov      ax, word ptr [0x2e2]
  0000:04EA  50                push     ax
  0000:04EB  e82f04            call     0x91d  ; -> sub_0000_091D
  0000:04EE  83c408            add      sp, 8
  0000:04F1  3dffff            cmp      ax, 0xffff
  0000:04F4  7523              jne      0x519  ; -> loc_0000_0519
  0000:04F6  8b16d802          mov      dx, word ptr [0x2d8]
  0000:04FA  2316dc02          and      dx, word ptr [0x2dc]
  0000:04FE  e81302            call     0x714  ; -> sub_0000_0714
  0000:0501  833e1302ff        cmp      word ptr [0x213], -1
  0000:0506  7f06              jg       0x50e  ; -> loc_0000_050E
  0000:0508  e89700            call     0x5a2  ; -> sub_0000_05A2
  0000:050B  eb56              jmp      0x563  ; -> loc_0000_0563
  0000:050D  db 90                                              ; |.|

loc_0000_050E:
  0000:050E  50                push     ax
  0000:050F  e85304            call     0x965  ; -> sub_0000_0965
  0000:0512  e85100            call     0x566  ; -> sub_0000_0566
  0000:0515  58                pop      ax
  0000:0516  eb4b              jmp      0x563  ; -> loc_0000_0563
  0000:0518  db 90                                              ; |.|

loc_0000_0519:
  0000:0519  a1da02            mov      ax, word ptr [0x2da]
  0000:051C  bb1100            mov      bx, 0x11
  0000:051F  f7eb              imul     bx
  0000:0521  50                push     ax
  0000:0522  b81c01            mov      ax, 0x11c
  0000:0525  50                push     ax
  0000:0526  a1e202            mov      ax, word ptr [0x2e2]
  0000:0529  50                push     ax
  0000:052A  e80204            call     0x92f  ; -> sub_0000_092F
  0000:052D  83c406            add      sp, 6
  0000:0530  33c0              xor      ax, ax
  0000:0532  50                push     ax
  0000:0533  50                push     ax
  0000:0534  a1e202            mov      ax, word ptr [0x2e2]
  0000:0537  50                push     ax
  0000:0538  e8f403            call     0x92f  ; -> sub_0000_092F
  0000:053B  83c406            add      sp, 6
  0000:053E  3dffff            cmp      ax, 0xffff
  0000:0541  7520              jne      0x563  ; -> loc_0000_0563
  0000:0543  8b16d802          mov      dx, word ptr [0x2d8]
  0000:0547  2316dc02          and      dx, word ptr [0x2dc]
  0000:054B  e8c601            call     0x714  ; -> sub_0000_0714
  0000:054E  833e1302ff        cmp      word ptr [0x213], -1
  0000:0553  7f06              jg       0x55b  ; -> loc_0000_055B
  0000:0555  e84a00            call     0x5a2  ; -> sub_0000_05A2
  0000:0558  eb09              jmp      0x563  ; -> loc_0000_0563
  0000:055A  db 90                                              ; |.|

loc_0000_055B:
  0000:055B  50                push     ax
  0000:055C  e8fa03            call     0x959  ; -> sub_0000_0959
  0000:055F  e80400            call     0x566  ; -> sub_0000_0566
  0000:0562  58                pop      ax

loc_0000_0563:
  0000:0563  5a                pop      dx
  0000:0564  5b                pop      bx
  0000:0565  c3                ret      

sub_0000_0566:
  0000:0566  52                push     dx
  0000:0567  a1e202            mov      ax, word ptr [0x2e2]
  0000:056A  50                push     ax
  0000:056B  e8a303            call     0x911  ; -> sub_0000_0911
  0000:056E  83c402            add      sp, 2
  0000:0571  3dffff            cmp      ax, 0xffff
  0000:0574  7515              jne      0x58b  ; -> loc_0000_058B
  0000:0576  833e1302ff        cmp      word ptr [0x213], -1
  0000:057B  7f06              jg       0x583  ; -> loc_0000_0583
  0000:057D  e82200            call     0x5a2  ; -> sub_0000_05A2
  0000:0580  eb1e              jmp      0x5a0  ; -> loc_0000_05A0
  0000:0582  db 90                                              ; |.|

loc_0000_0583:
  0000:0583  50                push     ax
  0000:0584  e8d803            call     0x95f  ; -> sub_0000_095F
  0000:0587  58                pop      ax
  0000:0588  eb16              jmp      0x5a0  ; -> loc_0000_05A0
  0000:058A  db 90                                              ; |.|

loc_0000_058B:
  0000:058B  8b16d802          mov      dx, word ptr [0x2d8]
  0000:058F  0b16de02          or       dx, word ptr [0x2de]
  0000:0593  e87e01            call     0x714  ; -> sub_0000_0714
  0000:0596  833eda0200        cmp      word ptr [0x2da], 0
  0000:059B  7503              jne      0x5a0  ; -> loc_0000_05A0
  0000:059D  e80f00            call     0x5af  ; -> sub_0000_05AF

loc_0000_05A0:
  0000:05A0  5a                pop      dx
  0000:05A1  c3                ret      

sub_0000_05A2:
  0000:05A2  50                push     ax
  0000:05A3  a1e202            mov      ax, word ptr [0x2e2]
  0000:05A6  50                push     ax
  0000:05A7  e88b03            call     0x935  ; -> sub_0000_0935
  0000:05AA  83c402            add      sp, 2
  0000:05AD  58                pop      ax
  0000:05AE  c3                ret      

sub_0000_05AF:
  0000:05AF  52                push     dx
  0000:05B0  b88402            mov      ax, 0x284
  0000:05B3  50                push     ax
  0000:05B4  e88403            call     0x93b  ; -> sub_0000_093B
  0000:05B7  83c402            add      sp, 2
  0000:05BA  8b16d802          mov      dx, word ptr [0x2d8]
  0000:05BE  2316dc02          and      dx, word ptr [0x2dc]
  0000:05C2  e84f01            call     0x714  ; -> sub_0000_0714
  0000:05C5  5a                pop      dx
  0000:05C6  c3                ret      

sub_0000_05C7:
  0000:05C7  50                push     ax
  0000:05C8  53                push     bx
  0000:05C9  51                push     cx
  0000:05CA  52                push     dx
  0000:05CB  e87303            call     0x941  ; -> sub_0000_0941
  0000:05CE  8bd8              mov      bx, ax
  0000:05D0  80e3fc            and      bl, 0xfc
  0000:05D3  e85100            call     0x627  ; -> sub_0000_0627
  0000:05D6  3d0200            cmp      ax, 2
  0000:05D9  7222              jb       0x5fd  ; -> loc_0000_05FD
  0000:05DB  53                push     bx
  0000:05DC  b430              mov      ah, 0x30
  0000:05DE  cd21              int      0x21  ; INT 21h/30h: Get DOS version
  0000:05E0  3d031e            cmp      ax, 0x1e03
  0000:05E3  5b                pop      bx
  0000:05E4  7214              jb       0x5fa  ; -> loc_0000_05FA
  0000:05E6  53                push     bx
  0000:05E7  b80844            mov      ax, 0x4408
  0000:05EA  bb0300            mov      bx, 3
  0000:05ED  cd21              int      0x21  ; INT 21h/44h: IOCTL
  0000:05EF  0bc0              or       ax, ax
  0000:05F1  5b                pop      bx
  0000:05F2  7406              je       0x5fa  ; -> loc_0000_05FA
  0000:05F4  b80200            mov      ax, 2
  0000:05F7  eb20              jmp      0x619  ; -> loc_0000_0619
  0000:05F9  db 90                                              ; |.|

loc_0000_05FA:
  0000:05FA  80e3f8            and      bl, 0xf8

loc_0000_05FD:
  0000:05FD  33c0              xor      ax, ax
  0000:05FF  0bdb              or       bx, bx
  0000:0601  7504              jne      0x607  ; -> loc_0000_0607
  0000:0603  0bd2              or       dx, dx
  0000:0605  7412              je       0x619  ; -> loc_0000_0619

loc_0000_0607:
  0000:0607  f7c30100          test     bx, 1
  0000:060B  750c              jne      0x619  ; -> loc_0000_0619
  0000:060D  d1cb              ror      bx, 1
  0000:060F  40                inc      ax
  0000:0610  3d1000            cmp      ax, 0x10
  0000:0613  75f2              jne      0x607  ; -> loc_0000_0607
  0000:0615  8bda              mov      bx, dx
  0000:0617  ebee              jmp      0x607  ; -> loc_0000_0607

loc_0000_0619:
  0000:0619  3d0000            cmp      ax, 0
  0000:061C  7503              jne      0x621  ; -> loc_0000_0621
  0000:061E  f9                stc      
  0000:061F  eb01              jmp      0x622  ; -> loc_0000_0622

loc_0000_0621:
  0000:0621  f8                clc      

loc_0000_0622:
  0000:0622  5a                pop      dx
  0000:0623  59                pop      cx
  0000:0624  5b                pop      bx
  0000:0625  58                pop      ax
  0000:0626  c3                ret      

sub_0000_0627:
  0000:0627  cd11              int      0x11  ; INT 11h
  0000:0629  25c000            and      ax, 0xc0
  0000:062C  d0c0              rol      al, 1
  0000:062E  d0c0              rol      al, 1
  0000:0630  c3                ret      

sub_0000_0631:
  0000:0631  06                push     es
  0000:0632  53                push     bx
  0000:0633  52                push     dx
  0000:0634  1e                push     ds
  0000:0635  07                pop      es
  0000:0636  8d16c701          lea      dx, [0x1c7]
  0000:063A  bbd402            mov      bx, 0x2d4
  0000:063D  b80602            mov      ax, 0x206
  0000:0640  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:0642  0bc0              or       ax, ax
  0000:0644  b8ffff            mov      ax, 0xffff
  0000:0647  7402              je       0x64b  ; -> loc_0000_064B
  0000:0649  33c0              xor      ax, ax

loc_0000_064B:
  0000:064B  5a                pop      dx
  0000:064C  5b                pop      bx
  0000:064D  07                pop      es
  0000:064E  c3                ret      

sub_0000_064F:
  0000:064F  06                push     es
  0000:0650  53                push     bx
  0000:0651  52                push     dx
  0000:0652  1e                push     ds
  0000:0653  07                pop      es
  0000:0654  8d16c701          lea      dx, [0x1c7]
  0000:0658  b80702            mov      ax, 0x207
  0000:065B  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:065D  0bc0              or       ax, ax
  0000:065F  b8ffff            mov      ax, 0xffff
  0000:0662  7402              je       0x666  ; -> loc_0000_0666
  0000:0664  33c0              xor      ax, ax

loc_0000_0666:
  0000:0666  5a                pop      dx
  0000:0667  5b                pop      bx
  0000:0668  07                pop      es
  0000:0669  c3                ret      

sub_0000_066A:
  0000:066A  06                push     es
  0000:066B  53                push     bx
  0000:066C  52                push     dx
  0000:066D  f9                stc      
  0000:066E  bb3f00            mov      bx, 0x3f
  0000:0671  b80070            mov      ax, 0x7000
  0000:0674  cd15              int      0x15  ; INT 15h, AH=70h
  0000:0676  fb                sti      
  0000:0677  7218              jb       0x691  ; -> loc_0000_0691
  0000:0679  e81f00            call     0x69b  ; -> sub_0000_069B
  0000:067C  7213              jb       0x691  ; -> loc_0000_0691
  0000:067E  c6061b0101        mov      byte ptr [0x11b], 1
  0000:0683  8916d802          mov      word ptr [0x2d8], dx
  0000:0687  2316de02          and      dx, word ptr [0x2de]
  0000:068B  7509              jne      0x696  ; -> loc_0000_0696
  0000:068D  f8                clc      
  0000:068E  eb07              jmp      0x697  ; -> loc_0000_0697
  0000:0690  db 90                                              ; |.|

loc_0000_0691:
  0000:0691  c6061b0100        mov      byte ptr [0x11b], 0

loc_0000_0696:
  0000:0696  f9                stc      

loc_0000_0697:
  0000:0697  5a                pop      dx
  0000:0698  5b                pop      bx
  0000:0699  07                pop      es
  0000:069A  c3                ret      

sub_0000_069B:
  0000:069B  e8c103            call     0xa5f  ; -> sub_0000_0A5F
  0000:069E  250080            and      ax, 0x8000
  0000:06A1  7411              je       0x6b4  ; -> loc_0000_06B4
  0000:06A3  e80f00            call     0x6b5  ; -> sub_0000_06B5
  0000:06A6  e8b603            call     0xa5f  ; -> sub_0000_0A5F
  0000:06A9  e82e00            call     0x6da  ; -> sub_0000_06DA
  0000:06AC  803ee80201        cmp      byte ptr [0x2e8], 1
  0000:06B1  7401              je       0x6b4  ; -> loc_0000_06B4
  0000:06B3  f9                stc      

loc_0000_06B4:
  0000:06B4  c3                ret      

sub_0000_06B5:
  0000:06B5  1e                push     ds
  0000:06B6  06                push     es
  0000:06B7  53                push     bx
  0000:06B8  52                push     dx
  0000:06B9  c606e80200        mov      byte ptr [0x2e8], 0
  0000:06BE  b81535            mov      ax, 0x3515
  0000:06C1  cd21              int      0x21  ; INT 21h/35h: Get interrupt vector
  0000:06C3  891ee402          mov      word ptr [0x2e4], bx
  0000:06C7  8c06e602          mov      word ptr [0x2e6], es
  0000:06CB  baed06            mov      dx, 0x6ed
  0000:06CE  0e                push     cs
  0000:06CF  1f                pop      ds
  0000:06D0  b81525            mov      ax, 0x2515
  0000:06D3  cd21              int      0x21  ; INT 21h/25h: Set interrupt vector
  0000:06D5  5a                pop      dx
  0000:06D6  5b                pop      bx
  0000:06D7  07                pop      es
  0000:06D8  1f                pop      ds
  0000:06D9  c3                ret      

sub_0000_06DA:
  0000:06DA  1e                push     ds
  0000:06DB  52                push     dx
  0000:06DC  8b16e402          mov      dx, word ptr [0x2e4]
  0000:06E0  a1e602            mov      ax, word ptr [0x2e6]
  0000:06E3  8ed8              mov      ds, ax
  0000:06E5  b81525            mov      ax, 0x2515
  0000:06E8  cd21              int      0x21  ; INT 21h/25h: Set interrupt vector
  0000:06EA  5a                pop      dx
  0000:06EB  1f                pop      ds
  0000:06EC  c3                ret      
  0000:06ED  db 83 EC 04 55 1E 50 8B EC 2E 8E 1E 25 00 3D 03 70 ; |...U.P.....%.=.p|
  0000:06FD  db 75 05 C6 06 E8 02 01 A1 E4 02 89 46 06 A1 E6 02 ; |u..........F....|
  0000:070D  db 89 46 08 58 1F 5D CB                            ; |.F.X.].|

sub_0000_0714:
  0000:0714  50                push     ax
  0000:0715  53                push     bx
  0000:0716  51                push     cx
  0000:0717  52                push     dx
  0000:0718  803e1b0101        cmp      byte ptr [0x11b], 1
  0000:071D  7515              jne      0x734  ; -> loc_0000_0734
  0000:071F  8bca              mov      cx, dx
  0000:0721  bb3f00            mov      bx, 0x3f
  0000:0724  b80070            mov      ax, 0x7000
  0000:0727  cd15              int      0x15  ; INT 15h, AH=70h
  0000:0729  3bd1              cmp      dx, cx
  0000:072B  7407              je       0x734  ; -> loc_0000_0734
  0000:072D  8bd1              mov      dx, cx
  0000:072F  b80170            mov      ax, 0x7001
  0000:0732  cd15              int      0x15  ; INT 15h, AH=70h

loc_0000_0734:
  0000:0734  8916d802          mov      word ptr [0x2d8], dx
  0000:0738  5a                pop      dx
  0000:0739  59                pop      cx
  0000:073A  5b                pop      bx
  0000:073B  58                pop      ax
  0000:073C  c3                ret      

sub_0000_073D:
  0000:073D  53                push     bx
  0000:073E  51                push     cx
  0000:073F  52                push     dx
  0000:0740  57                push     di
  0000:0741  56                push     si
  0000:0742  8b0eda02          mov      cx, word ptr [0x2da]
  0000:0746  e325              jcxz     0x76d  ; -> loc_0000_076D
  0000:0748  8d3ec701          lea      di, [0x1c7]
  0000:074C  8a16c601          mov      dl, byte ptr [0x1c6]
  0000:0750  be1c01            mov      si, 0x11c
  0000:0753  3814              cmp      byte ptr [si], dl
  0000:0755  7403              je       0x75a  ; -> loc_0000_075A
  0000:0757  eb0f              jmp      0x768  ; -> loc_0000_0768
  0000:0759  db 90                                              ; |.|

loc_0000_075A:
  0000:075A  8bde              mov      bx, si
  0000:075C  8d7701            lea      si, [bx + 1]
  0000:075F  e84900            call     0x7ab  ; -> sub_0000_07AB
  0000:0762  8bf3              mov      si, bx
  0000:0764  0bc0              or       ax, ax
  0000:0766  7505              jne      0x76d  ; -> loc_0000_076D

loc_0000_0768:
  0000:0768  83c611            add      si, 0x11
  0000:076B  e2e6              loop     0x753

loc_0000_076D:
  0000:076D  e309              jcxz     0x778  ; -> loc_0000_0778
  0000:076F  a1da02            mov      ax, word ptr [0x2da]
  0000:0772  2bc1              sub      ax, cx
  0000:0774  40                inc      ax
  0000:0775  eb04              jmp      0x77b  ; -> loc_0000_077B
  0000:0777  db 90                                              ; |.|

loc_0000_0778:
  0000:0778  b8ffff            mov      ax, 0xffff

loc_0000_077B:
  0000:077B  5e                pop      si
  0000:077C  5f                pop      di
  0000:077D  5a                pop      dx
  0000:077E  59                pop      cx
  0000:077F  5b                pop      bx
  0000:0780  c3                ret      

sub_0000_0781:
  0000:0781  51                push     cx
  0000:0782  57                push     di
  0000:0783  06                push     es
  0000:0784  1e                push     ds
  0000:0785  07                pop      es
  0000:0786  b9ff7f            mov      cx, 0x7fff
  0000:0789  33c0              xor      ax, ax
  0000:078B  3a05              cmp      al, byte ptr [di]
  0000:078D  7409              je       0x798  ; -> loc_0000_0798
  0000:078F  fc                cld      
  0000:0790  f2ae              repne scasb al, byte ptr es:[di]
  0000:0792  41                inc      cx
  0000:0793  b8ff7f            mov      ax, 0x7fff
  0000:0796  2bc1              sub      ax, cx

loc_0000_0798:
  0000:0798  07                pop      es
  0000:0799  5f                pop      di
  0000:079A  59                pop      cx
  0000:079B  c3                ret      

sub_0000_079C:
  0000:079C  06                push     es
  0000:079D  57                push     di
  0000:079E  56                push     si
  0000:079F  1e                push     ds
  0000:07A0  07                pop      es

loc_0000_07A1:
  0000:07A1  ac                lodsb    al, byte ptr [si]
  0000:07A2  aa                stosb    byte ptr es:[di], al
  0000:07A3  3c00              cmp      al, 0
  0000:07A5  75fa              jne      0x7a1  ; -> loc_0000_07A1
  0000:07A7  5e                pop      si
  0000:07A8  5f                pop      di
  0000:07A9  07                pop      es
  0000:07AA  c3                ret      

sub_0000_07AB:
  0000:07AB  06                push     es
  0000:07AC  51                push     cx
  0000:07AD  57                push     di
  0000:07AE  56                push     si
  0000:07AF  1e                push     ds
  0000:07B0  07                pop      es
  0000:07B1  e8cdff            call     0x781  ; -> sub_0000_0781
  0000:07B4  8bc8              mov      cx, ax
  0000:07B6  41                inc      cx
  0000:07B7  33c0              xor      ax, ax
  0000:07B9  fc                cld      
  0000:07BA  f3a6              repe cmpsb byte ptr [si], byte ptr es:[di]
  0000:07BC  7501              jne      0x7bf  ; -> loc_0000_07BF
  0000:07BE  40                inc      ax

loc_0000_07BF:
  0000:07BF  5e                pop      si
  0000:07C0  5f                pop      di
  0000:07C1  59                pop      cx
  0000:07C2  07                pop      es
  0000:07C3  c3                ret      
  0000:07C4  db 06 53 1E 07 B8 08 02 BA 02 02 BB FE 01 CD E0 0B ; |.S..............|
  0000:07D4  db C0 7E 16 C6 06 12 02 01 B8 06 02 CD E0 0B C0 B8 ; |.~..............|
  0000:07E4  db FF FF 74 02 33 C0 5B 07 C3 BA 0C 02 B8 08 02 CD ; |..t.3.[.........|
  0000:07F4  db E0 0B C0 7E DE C6 06 12 02 00 EB DC 52 06 80 3E ; |...~........R..>|
  0000:0804  db 12 02 00 74 05 BA 02 02 EB 03 BA 0C 02 B8 07 02 ; |...t............|
  0000:0814  db 1E 07 CD E0 B8 8C 08 A3 FE 01 8C C8 A3 00 02 07 ; |................|
  0000:0824  db 5A C3                                           ; |Z.|

sub_0000_0826:
  0000:0826  06                push     es
  0000:0827  53                push     bx
  0000:0828  1e                push     ds
  0000:0829  07                pop      es
  0000:082A  ba0c02            mov      dx, 0x20c
  0000:082D  bb0802            mov      bx, 0x208
  0000:0830  b80602            mov      ax, 0x206
  0000:0833  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:0835  0bc0              or       ax, ax
  0000:0837  b8ffff            mov      ax, 0xffff
  0000:083A  7429              je       0x865  ; -> loc_0000_0865
  0000:083C  a10802            mov      ax, word ptr [0x208]
  0000:083F  a3fe01            mov      word ptr [0x1fe], ax
  0000:0842  a10a02            mov      ax, word ptr [0x20a]
  0000:0845  a30002            mov      word ptr [0x200], ax
  0000:0848  b80802            mov      ax, 0x208
  0000:084B  ba0202            mov      dx, 0x202
  0000:084E  bbfe01            mov      bx, 0x1fe
  0000:0851  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:0853  0bc0              or       ax, ax
  0000:0855  7e07              jle      0x85e  ; -> loc_0000_085E
  0000:0857  c606120201        mov      byte ptr [0x212], 1
  0000:085C  eb05              jmp      0x863  ; -> loc_0000_0863

loc_0000_085E:
  0000:085E  c606120200        mov      byte ptr [0x212], 0

loc_0000_0863:
  0000:0863  33c0              xor      ax, ax

loc_0000_0865:
  0000:0865  5b                pop      bx
  0000:0866  07                pop      es
  0000:0867  c3                ret      
  0000:0868  db 52 BA 0C 02 B8 07 02 06 1E 07 CD E0 07 B8 88 08 ; |R...............|
  0000:0878  db A3 08 02 A3 FE 01 8C C8 A3 0A 02 A3 00 02 5A C3 ; |..............Z.|
  0000:0888  db B8 FF FF CB B8 FF FF CB                         ; |........|

loc_0000_0890:
  0000:0890  803e120201        cmp      byte ptr [0x212], 1
  0000:0895  7411              je       0x8a8  ; -> loc_0000_08A8
  0000:0897  3d3900            cmp      ax, 0x39
  0000:089A  7c0c              jl       0x8a8  ; -> loc_0000_08A8
  0000:089C  7407              je       0x8a5  ; -> loc_0000_08A5
  0000:089E  3d4400            cmp      ax, 0x44
  0000:08A1  7e2c              jle      0x8cf  ; -> loc_0000_08CF
  0000:08A3  eb03              jmp      0x8a8  ; -> loc_0000_08A8

loc_0000_08A5:
  0000:08A5  b8ae00            mov      ax, 0xae

loc_0000_08A8:
  0000:08A8  8f061702          pop      word ptr [0x217]
  0000:08AC  ff361502          push     word ptr [0x215]
  0000:08B0  ff361702          push     word ptr [0x217]
  0000:08B4  53                push     bx
  0000:08B5  8bdc              mov      bx, sp
  0000:08B7  1e                push     ds
  0000:08B8  06                push     es
  0000:08B9  16                push     ss
  0000:08BA  07                pop      es
  0000:08BB  ff1efe01          lcall    [0x1fe]
  0000:08BF  07                pop      es
  0000:08C0  1f                pop      ds
  0000:08C1  5b                pop      bx
  0000:08C2  8f061702          pop      word ptr [0x217]
  0000:08C6  8f061502          pop      word ptr [0x215]
  0000:08CA  ff361702          push     word ptr [0x217]

loc_0000_08CE:
  0000:08CE  c3                ret      

loc_0000_08CF:
  0000:08CF  b8ffff            mov      ax, 0xffff
  0000:08D2  ebfa              jmp      0x8ce  ; -> loc_0000_08CE

loc_0000_08D4:
  0000:08D4  803e120201        cmp      byte ptr [0x212], 1
  0000:08D9  740a              je       0x8e5  ; -> loc_0000_08E5
  0000:08DB  3dbe00            cmp      ax, 0xbe
  0000:08DE  742c              je       0x90c  ; -> loc_0000_090C
  0000:08E0  3dbf00            cmp      ax, 0xbf
  0000:08E3  7427              je       0x90c  ; -> loc_0000_090C

loc_0000_08E5:
  0000:08E5  8f061702          pop      word ptr [0x217]
  0000:08E9  ff361502          push     word ptr [0x215]
  0000:08ED  ff361702          push     word ptr [0x217]
  0000:08F1  53                push     bx
  0000:08F2  8bdc              mov      bx, sp
  0000:08F4  1e                push     ds
  0000:08F5  06                push     es
  0000:08F6  16                push     ss
  0000:08F7  07                pop      es
  0000:08F8  ff1e0802          lcall    [0x208]
  0000:08FC  07                pop      es
  0000:08FD  1f                pop      ds
  0000:08FE  5b                pop      bx
  0000:08FF  8f061702          pop      word ptr [0x217]
  0000:0903  8f061502          pop      word ptr [0x215]
  0000:0907  ff361702          push     word ptr [0x217]

loc_0000_090B:
  0000:090B  c3                ret      

loc_0000_090C:
  0000:090C  b8ffff            mov      ax, 0xffff
  0000:090F  ebfa              jmp      0x90b  ; -> loc_0000_090B

sub_0000_0911:
  0000:0911  b80100            mov      ax, 1
  0000:0914  e979ff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0917:
  0000:0917  b80200            mov      ax, 2
  0000:091A  e973ff            jmp      0x890  ; -> loc_0000_0890

sub_0000_091D:
  0000:091D  b80400            mov      ax, 4
  0000:0920  e96dff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0923:
  0000:0923  b80500            mov      ax, 5
  0000:0926  e967ff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0929:
  0000:0929  b80600            mov      ax, 6
  0000:092C  e961ff            jmp      0x890  ; -> loc_0000_0890

sub_0000_092F:
  0000:092F  b80700            mov      ax, 7
  0000:0932  e95bff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0935:
  0000:0935  b80800            mov      ax, 8
  0000:0938  e955ff            jmp      0x890  ; -> loc_0000_0890

sub_0000_093B:
  0000:093B  b81300            mov      ax, 0x13
  0000:093E  e94fff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0941:
  0000:0941  b81900            mov      ax, 0x19
  0000:0944  e949ff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0947:
  0000:0947  b81c00            mov      ax, 0x1c
  0000:094A  e987ff            jmp      0x8d4  ; -> loc_0000_08D4

sub_0000_094D:
  0000:094D  b81d00            mov      ax, 0x1d
  0000:0950  e981ff            jmp      0x8d4  ; -> loc_0000_08D4

sub_0000_0953:
  0000:0953  b81e00            mov      ax, 0x1e
  0000:0956  e97bff            jmp      0x8d4  ; -> loc_0000_08D4

sub_0000_0959:
  0000:0959  b81f00            mov      ax, 0x1f
  0000:095C  e975ff            jmp      0x8d4  ; -> loc_0000_08D4

sub_0000_095F:
  0000:095F  b82000            mov      ax, 0x20
  0000:0962  e96fff            jmp      0x8d4  ; -> loc_0000_08D4

sub_0000_0965:
  0000:0965  b82100            mov      ax, 0x21
  0000:0968  e969ff            jmp      0x8d4  ; -> loc_0000_08D4

sub_0000_096B:
  0000:096B  b83800            mov      ax, 0x38
  0000:096E  e91fff            jmp      0x890  ; -> loc_0000_0890

sub_0000_0971:
  0000:0971  55                push     bp
  0000:0972  8bec              mov      bp, sp
  0000:0974  1e                push     ds
  0000:0975  06                push     es
  0000:0976  56                push     si
  0000:0977  57                push     di
  0000:0978  53                push     bx
  0000:0979  51                push     cx
  0000:097A  52                push     dx
  0000:097B  b80006            mov      ax, 0x600
  0000:097E  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:0980  250080            and      ax, 0x8000
  0000:0983  7413              je       0x998  ; -> loc_0000_0998
  0000:0985  ba2402            mov      dx, 0x224
  0000:0988  1e                push     ds
  0000:0989  07                pop      es
  0000:098A  b80e06            mov      ax, 0x60e
  0000:098D  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:098F  0bc0              or       ax, ax
  0000:0991  7405              je       0x998  ; -> loc_0000_0998
  0000:0993  3d6e00            cmp      ax, 0x6e
  0000:0996  7c03              jl       0x99b  ; -> loc_0000_099B

loc_0000_0998:
  0000:0998  e98d00            jmp      0xa28  ; -> loc_0000_0A28

loc_0000_099B:
  0000:099B  8b4608            mov      ax, word ptr [bp + 8]
  0000:099E  a32202            mov      word ptr [0x222], ax
  0000:09A1  83ec41            sub      sp, 0x41
  0000:09A4  8bfc              mov      di, sp
  0000:09A6  57                push     di
  0000:09A7  16                push     ss
  0000:09A8  07                pop      es
  0000:09A9  8b7604            mov      si, word ptr [bp + 4]
  0000:09AC  b94100            mov      cx, 0x41
  0000:09AF  fc                cld      
  0000:09B0  f3a4              rep movsb byte ptr es:[di], byte ptr [si]
  0000:09B2  5f                pop      di
  0000:09B3  83ec41            sub      sp, 0x41
  0000:09B6  8bf4              mov      si, sp
  0000:09B8  83ec61            sub      sp, 0x61
  0000:09BB  8bdc              mov      bx, sp
  0000:09BD  b104              mov      cl, 4
  0000:09BF  d3eb              shr      bx, cl
  0000:09C1  8cd2              mov      dx, ss
  0000:09C3  03d3              add      dx, bx
  0000:09C5  81ea9701          sub      dx, 0x197
  0000:09C9  b104              mov      cl, 4
  0000:09CB  d3e3              shl      bx, cl
  0000:09CD  8bcc              mov      cx, sp
  0000:09CF  2bcb              sub      cx, bx
  0000:09D1  81c17019          add      cx, 0x1970
  0000:09D5  89362002          mov      word ptr [0x220], si
  0000:09D9  2bf3              sub      si, bx
  0000:09DB  2bfb              sub      di, bx
  0000:09DD  81c67019          add      si, 0x1970
  0000:09E1  81c77019          add      di, 0x1970
  0000:09E5  fa                cli      
  0000:09E6  8c161c02          mov      word ptr [0x21c], ss
  0000:09EA  89261e02          mov      word ptr [0x21e], sp
  0000:09EE  8ed2              mov      ss, dx
  0000:09F0  8be1              mov      sp, cx
  0000:09F2  fb                sti      
  0000:09F3  8cd0              mov      ax, ss
  0000:09F5  8ec0              mov      es, ax
  0000:09F7  8b1e2202          mov      bx, word ptr [0x222]
  0000:09FB  b80306            mov      ax, 0x603
  0000:09FE  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:0A00  fa                cli      
  0000:0A01  8e161c02          mov      ss, word ptr [0x21c]
  0000:0A05  8b261e02          mov      sp, word ptr [0x21e]
  0000:0A09  fb                sti      
  0000:0A0A  0bc0              or       ax, ax
  0000:0A0C  7e0f              jle      0xa1d  ; -> loc_0000_0A1D
  0000:0A0E  8b7e06            mov      di, word ptr [bp + 6]
  0000:0A11  1e                push     ds
  0000:0A12  07                pop      es
  0000:0A13  8b362002          mov      si, word ptr [0x220]
  0000:0A17  b94100            mov      cx, 0x41
  0000:0A1A  fc                cld      
  0000:0A1B  f3a4              rep movsb byte ptr es:[di], byte ptr [si]

loc_0000_0A1D:
  0000:0A1D  83c461            add      sp, 0x61
  0000:0A20  83c441            add      sp, 0x41
  0000:0A23  83c441            add      sp, 0x41
  0000:0A26  eb10              jmp      0xa38  ; -> loc_0000_0A38

loc_0000_0A28:
  0000:0A28  1e                push     ds
  0000:0A29  07                pop      es
  0000:0A2A  8b5e08            mov      bx, word ptr [bp + 8]
  0000:0A2D  8b7606            mov      si, word ptr [bp + 6]
  0000:0A30  8b7e04            mov      di, word ptr [bp + 4]
  0000:0A33  b80306            mov      ax, 0x603
  0000:0A36  cde0              int      0xe0  ; INT E0h, AH=06h

loc_0000_0A38:
  0000:0A38  5a                pop      dx
  0000:0A39  59                pop      cx
  0000:0A3A  5b                pop      bx
  0000:0A3B  5f                pop      di
  0000:0A3C  5e                pop      si
  0000:0A3D  07                pop      es
  0000:0A3E  1f                pop      ds
  0000:0A3F  5d                pop      bp
  0000:0A40  c3                ret      

loc_0000_0A41:
  0000:0A41  55                push     bp
  0000:0A42  8bec              mov      bp, sp
  0000:0A44  83c504            add      bp, 4
  0000:0A47  06                push     es
  0000:0A48  1e                push     ds
  0000:0A49  07                pop      es
  0000:0A4A  cde0              int      0xe0  ; INT E0h
  0000:0A4C  07                pop      es
  0000:0A4D  5d                pop      bp
  0000:0A4E  c3                ret      

loc_0000_0A4F:
  0000:0A4F  55                push     bp
  0000:0A50  8bec              mov      bp, sp
  0000:0A52  06                push     es
  0000:0A53  57                push     di
  0000:0A54  1e                push     ds
  0000:0A55  07                pop      es
  0000:0A56  8b7e04            mov      di, word ptr [bp + 4]
  0000:0A59  cde0              int      0xe0  ; INT E0h
  0000:0A5B  5f                pop      di
  0000:0A5C  07                pop      es
  0000:0A5D  5d                pop      bp
  0000:0A5E  c3                ret      

sub_0000_0A5F:
  0000:0A5F  b80006            mov      ax, 0x600
  0000:0A62  e9dcff            jmp      0xa41  ; -> loc_0000_0A41

sub_0000_0A65:
  0000:0A65  b80106            mov      ax, 0x601
  0000:0A68  e9e4ff            jmp      0xa4f  ; -> loc_0000_0A4F

sub_0000_0A6B:
  0000:0A6B  b80406            mov      ax, 0x604
  0000:0A6E  e9deff            jmp      0xa4f  ; -> loc_0000_0A4F

sub_0000_0A71:
  0000:0A71  06                push     es
  0000:0A72  53                push     bx
  0000:0A73  52                push     dx
  0000:0A74  1e                push     ds
  0000:0A75  07                pop      es
  0000:0A76  bb2a02            mov      bx, 0x22a
  0000:0A79  ba2e02            mov      dx, 0x22e
  0000:0A7C  b80602            mov      ax, 0x206
  0000:0A7F  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:0A81  9ae10a0000        lcall    0, 0xae1  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:0A86  5a                pop      dx
  0000:0A87  5b                pop      bx
  0000:0A88  07                pop      es
  0000:0A89  c3                ret      

sub_0000_0A8A:
  0000:0A8A  06                push     es
  0000:0A8B  52                push     dx
  0000:0A8C  1e                push     ds
  0000:0A8D  07                pop      es
  0000:0A8E  ba2e02            mov      dx, 0x22e
  0000:0A91  b80702            mov      ax, 0x207
  0000:0A94  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:0A96  5a                pop      dx
  0000:0A97  07                pop      es
  0000:0A98  c3                ret      
  0000:0A99  db E8 D5 FF E8 30 00 C3 E8 32 00 E8 E4 FF C3       ; |....0...2.....|

loc_0000_0AA7:
  0000:0AA7  55                push     bp
  0000:0AA8  8bec              mov      bp, sp
  0000:0AAA  83c504            add      bp, 4
  0000:0AAD  9a080b0000        lcall    0, 0xb08  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:0AB2  3dffff            cmp      ax, 0xffff
  0000:0AB5  7416              je       0xacd  ; -> loc_0000_0ACD
  0000:0AB7  3dfeff            cmp      ax, 0xfffe
  0000:0ABA  7411              je       0xacd  ; -> loc_0000_0ACD
  0000:0ABC  9a370b0000        lcall    0, 0xb37  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:0AC1  a33402            mov      word ptr [0x234], ax
  0000:0AC4  ff1e2a02          lcall    [0x22a]
  0000:0AC8  9a610b0000        lcall    0, 0xb61  ; -> sub_0000_0000 | RELOC->seg_0000

loc_0000_0ACD:
  0000:0ACD  5d                pop      bp
  0000:0ACE  c3                ret      
  0000:0ACF  db B8 D6 20 E9 D2 FF B8 D7 20 E9 CC FF             ; |.. ..... ...|

sub_0000_0ADB:
  0000:0ADB  b8e920            mov      ax, 0x20e9
  0000:0ADE  e9c6ff            jmp      0xaa7  ; -> loc_0000_0AA7
  0000:0AE1  db 50 B8 D5 20 25 FF 0F FF 1E 2A 02 C7 06 36 02 FF ; |P.. %....*...6..|
  0000:0AF1  db 0F 3C 20 7E 10 C7 06 36 02 FF FF 3C 37 7E 06 C7 ; |.< ~...6...<7~..|
  0000:0B01  db 06 36 02 FF EF 58 CB 81 3E 36 02 FF 0F 74 11 81 ; |.6...X..>6...t..|
  0000:0B11  db 3E 36 02 FF EF 74 1E                            ; |>6...t.|
  0000:0B18  db 3D 44 21 7E                                     ; "=D!~"
  0000:0B1C  db 19 B8 FF FF CB 3D 0A 21 7F 05 23 06 36 02 CB 3D ; |.....=.!..#.6..=|
  0000:0B2C  db 2D 21 B8 FE FF 74 03 B8 FF FF CB 9C 3D 90 20 75 ; |-!...t......=. u|
  0000:0B3C  db 22 81 3E 36 02 FF 0F 74 1A 50 B8 D5 20 FF 1E 2A ; |".>6...t.P.. ..*|
  0000:0B4C  db 02 3C 29 58 7F 0D 53 8B 5D 0E 8B 1F D1 E3 43 29 ; |.<)X..S.].....C)|
  0000:0B5C  db 5D 02 5B 9D CB 9C 81 3E 34 02 90 20 74 0A 81 3E ; |].[....>4.. t..>|
  0000:0B6C  db 34 02 17 21 74 02 9D CB 81 3E 36 02 FF 0F 74 6A ; |4..!t....>6...tj|
  0000:0B7C  db 50 B8 D5 20 FF 1E 2A 02 3C 29 7F 18 81 3E 34 02 ; |P.. ..*.<)...>4.|
  0000:0B8C  db 17 21 74 10 58 53 8B 5D 0E 8B 1F D1 E3 43 01 5D ; |.!t.XS.].....C.]|
  0000:0B9C  db 02 5B EB                                        ; |.[.|
  0000:0B9F  db 46 3C 37 58                                     ; "F<7X"
  0000:0BA3  db 7F 41 81 3E 34 02 17                            ; |.A.>4..|
  0000:0BAA  db 21 75 39 56 57 51 52                            ; "!u9VWQR"
  0000:0BB1  db 8B 76 00 83 C6 04 E8 2E 00 32 E4 B1 04 F6 E1 BF ; |.v.......2......|
  0000:0BC1  db 38 02 03 F8 B9 04 00 B8 00 00                   ; |8.........|
  0000:0BCB  db 4E 4F 47 46                                     ; "NOGF"
  0000:0BCF  db 8A 15 0A 14 74 0D 8A 15 38 14 75 04 E2 F0 EB 03 ; |....t...8.u.....|
  0000:0BDF  db B8 FF FF                                        ; |...|
  0000:0BE2  db 5A 59 5F 5E                                     ; "ZY_^"
  0000:0BE6  db 9D CB 55 83 EC 0B 8B EC 1E 1E 07 16 1F 8D 46 00 ; |..U...........F.|
  0000:0BF6  db 55 50 8B EC B8 31 20 25 FF 0F 26 FF 1E 2A 02 83 ; |UP...1 %..&..*..|
  0000:0C06  db C4 02 5D 1F 8A 46 00 83 C4 0B                   ; |..]..F....|

; ------------------------------------------------------------------------
; SEGMENT seg_00C1  (644 bytes, file 0x0E10-0x1094)
; ------------------------------------------------------------------------
seg_00C1:

  00C1:0000  db 5D C3                                           ; |].|
  00C1:0002  db 43 72 65 61 74 65 20 53 74 61 72 74 75 70       ; "Create Startup"
  00C1:0010  db 00                                                ; NUL
  00C1:0011  db 54 6F 20 70 72 65 76 65 6E 74 20 61 6E 20 61 64 ; "To prevent an additional disk swap, we need to write a file ..."
  00C1:0021  db 64 69 74 69 6F 6E 61 6C 20 64 69 73 6B 20 73 77
  00C1:0031  db 61 70 2C 20 77 65 20 6E 65 65 64 20 74 6F 20 77
  00C1:0041  db 72 69 74 65 20 61 20 66 69 6C 65 20 6F 6E 20 74
  00C1:0051  db 68 65 20 44 65 73 6B 4D 61 74 65 20 73 74 61 72
  00C1:0061  db 74 75 70 20 64 69 73 6B 2E
  00C1:006A  db 00                                                ; NUL
  00C1:006B  db 50 6C 65 61 73 65 20 69 6E 73 65 72 74 20 74 68 ; "Please insert the disk containing DESK.EXE into drive X:"
  00C1:007B  db 65 20 64 69 73 6B 20 63 6F 6E 74 61 69 6E 69 6E
  00C1:008B  db 67 20 44 45 53 4B 2E 45 58 45 20 69 6E 74 6F 20
  00C1:009B  db 64 72 69 76 65 20 58 3A
  00C1:00A3  db 00                                                ; NUL
  00C1:00A4  db 49 6E 73 65 72 74 20 74 68 65 20 64 69 73 6B 20 ; "Insert the disk you wish to have startup information stored ..."
  00C1:00B4  db 79 6F 75 20 77 69 73 68 20 74 6F 20 68 61 76 65
  00C1:00C4  db 20 73 74 61 72 74 75 70 20 69 6E 66 6F 72 6D 61
  00C1:00D4  db 74 69 6F 6E 20 73 74 6F 72 65 64 20 6F 6E 20 69
  00C1:00E4  db 6E 20 64 72 69 76 65 20 58 3A
  00C1:00EE  db 00                                                ; NUL
  00C1:00EF  db 00 00                                           ; |..|
  00C1:00F1  db 41 55 54 4F 4C 4F 41 44 69                      ; "AUTOLOADi"
  00C1:00FA  db 00                                                ; NUL
  00C1:00FB  db 00 00 81 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................| [RELOC->seg_0000]
  00C1:010B  db 00 00 00 00 00 00 00 00 03 00 06 01 02 00 00 00 ; |................|
  00C1:011B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:012B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:013B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:014B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:015B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:016B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:017B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:018B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:019B  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:01AB  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:01BB  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:01CB  db 00 00 00 00 00 00 00 00 00 00 00 00 00          ; |.............|
  00C1:01D8  db 58 3A 5C 41 55 54 4F 4C 4F 41 44 2E 43 46 47    ; "X:\AUTOLOAD.CFG"
  00C1:01E7  db 00                                                ; NUL
  00C1:01E8  db 43 4F 4D 53 50 45 43 3D                         ; "COMSPEC="
  00C1:01F0  db 00                                                ; NUL
  00C1:01F1  db 58 3A 5C 44 45 53 4B 2E 45 58 45                ; "X:\DESK.EXE"
  00C1:01FC  db 00                                                ; NUL
  00C1:01FD  db 00 CD AB BA DC                                  ; |.....|
  00C1:0202  db 50 52 47 55 46                                  ; "PRGUF"
  00C1:0207  db 00                                                ; NUL
  00C1:0208  db CD AB BA DC                                     ; |....|
  00C1:020C  db 44 4D 47 55 46                                  ; "DMGUF"
  00C1:0211  db 00                                                ; NUL
  00C1:0212  db 00 00 00 13 02 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  00C1:0222  db 00 00                                           ; |..|
  00C1:0224  db 50 52 47 55 46                                  ; "PRGUF"
  00C1:0229  db 00                                                ; NUL
  00C1:022A  db CD AB BA DC                                     ; |....|
  00C1:022E  db 44 4D 43 53 52                                  ; "DMCSR"
  00C1:0233  db 00                                                ; NUL
  00C1:0234  db 00 00 00 00                                     ; |....|
  00C1:0238  db 31 30 30 30 43 47 41                            ; "1000CGA"
  00C1:023F  db 00                                                ; NUL
  00C1:0240  db 44 44 47 41 45 47 41                            ; "DDGAEGA"
  00C1:0247  db 00                                                ; NUL
  00C1:0248  db 48 45 52 43 50 4C 41 4E 54 43 31 36 54 43 34    ; "HERCPLANTC16TC4"
  00C1:0257  db 00                                                ; NUL
  00C1:0258  db 56 47 41 00                                     ; |VGA.|
  00C1:025C  db 4D 43 47 41 45 47 41                            ; "MCGAEGA"
  00C1:0263  db 00                                                ; NUL
  00C1:0264  db 4C 52 45 53 54 32 35 36 54 43 34 30 48          ; "LREST256TC40H"
  00C1:0271  db 00                                                ; NUL
  00C1:0272  db 00 00 43 00 00 00 4D 00 00 00 45 00 00 00 54 00 ; |..C...M...E...T.|
  00C1:0282  db 00 00                                           ; |..|