; ========================================================================
; Disassembly of /Users/joe/Documents/GitHub/bayside/archive/deskmate-3.05/extracted/D87.RES
; Generated by disasm_mz.py (Bayside project)
; ========================================================================

; MZ Header:
;   File size:        818 bytes
;   Header size:      512 bytes
;   Code size:        306 bytes
;   Pages:            2
;   Relocations:      3
;   Entry point:      0000:0000
;   Init SS:SP:       0014:0002
;   Min alloc:        0x0000 paragraphs
;   Max alloc:        0x0001 paragraphs

; Segment Map:
;   seg_0000  file=0x0200  (CODE/DATA)
;   seg_0008  file=0x0280  (CODE/DATA)
;   seg_0014  file=0x0340  (BSS)

; Relocation Table (3 entries):
;   0008:000C  file=0x028C  value=seg_0000
;   0000:0003  file=0x0203  value=seg_0008
;   0000:003A  file=0x023A  value=seg_0008

; Analysis Summary:
;   Instructions:     133
;   Functions (CALL): 0
;   Jump targets:     8
;   Strings:          0
;   INT calls:        8

; ========================================================================
; CODE / DATA
; ========================================================================

; ------------------------------------------------------------------------
; SEGMENT seg_0000  (128 bytes, file 0x0200-0x0280)
; ------------------------------------------------------------------------
seg_0000:


entry_point:
  0000:0000  8cc1              mov      cx, es
  0000:0002  b80800            mov      ax, 8  ; RELOC->seg_0008
  0000:0005  8ed8              mov      ds, ax
  0000:0007  8ec0              mov      es, ax
  0000:0009  890e2200          mov      word ptr [0x22], cx
  0000:000D  b80006            mov      ax, 0x600
  0000:0010  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:0012  bb0200            mov      bx, 2
  0000:0015  250080            and      ax, 0x8000
  0000:0018  50                push     ax
  0000:0019  7405              je       0x20  ; -> loc_0000_0020
  0000:001B  b8f001            mov      ax, 0x1f0
  0000:001E  eb03              jmp      0x23  ; -> loc_0000_0023

loc_0000_0020:
  0000:0020  b8ff01            mov      ax, 0x1ff

loc_0000_0023:
  0000:0023  cde0              int      0xe0  ; INT E0h, AH=01h
  0000:0025  58                pop      ax
  0000:0026  0bc0              or       ax, ax
  0000:0028  7502              jne      0x2c  ; -> loc_0000_002C
  0000:002A  fec8              dec      al

loc_0000_002C:
  0000:002C  8ec1              mov      es, cx
  0000:002E  268b1e0200        mov      bx, word ptr es:[2]
  0000:0033  2bd9              sub      bx, cx
  0000:0035  b431              mov      ah, 0x31
  0000:0037  cd21              int      0x21  ; INT 21h/31h: TSR (keep process)
  0000:0039  b80800            mov      ax, 8  ; RELOC->seg_0008
  0000:003C  8ed8              mov      ds, ax
  0000:003E  8ec0              mov      es, ax
  0000:0040  ba2700            mov      dx, 0x27
  0000:0043  bbb200            mov      bx, 0xb2
  0000:0046  b80602            mov      ax, 0x206
  0000:0049  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:004B  48                dec      ax
  0000:004C  7526              jne      0x74  ; -> loc_0000_0074
  0000:004E  bfa400            mov      di, 0xa4
  0000:0051  57                push     di
  0000:0052  8bec              mov      bp, sp
  0000:0054  b80606            mov      ax, 0x606
  0000:0057  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:0059  83c402            add      sp, 2
  0000:005C  bf2d00            mov      di, 0x2d
  0000:005F  57                push     di
  0000:0060  8bec              mov      bp, sp
  0000:0062  b8e920            mov      ax, 0x20e9
  0000:0065  ff1eb200          lcall    [0xb2]
  0000:0069  83c402            add      sp, 2
  0000:006C  ba2700            mov      dx, 0x27
  0000:006F  b80702            mov      ax, 0x207
  0000:0072  cde0              int      0xe0  ; INT E0h, AH=02h

loc_0000_0074:
  0000:0074  ba0200            mov      dx, 2
  0000:0077  b80702            mov      ax, 0x207
  0000:007A  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:007C  b8004c            mov      ax, 0x4c00
  0000:007F  cd21              int      0x21  ; INT 21h/4Ch: Exit with return code

; ------------------------------------------------------------------------
; SEGMENT seg_0008  (178 bytes, file 0x0280-0x0332)
; ------------------------------------------------------------------------
seg_0008:

  0008:0000  db 21                                              ; |!|
  0008:0001  004438            add      byte ptr [si + 0x38], al
  0008:0004  37                aaa      
  0008:0005  0000              add      byte ptr [bx + si], al
  0008:0007  0000              add      byte ptr [bx + si], al
  0008:0009  0039              add      byte ptr [bx + di], bh
  0008:000B  0000              add      byte ptr [bx + si], al  ; RELOC->seg_0000
  0008:000D  0000              add      byte ptr [bx + si], al
  0008:000F  0000              add      byte ptr [bx + si], al
  0008:0011  0000              add      byte ptr [bx + si], al
  0008:0013  0000              add      byte ptr [bx + si], al
  0008:0015  0000              add      byte ptr [bx + si], al
  0008:0017  0000              add      byte ptr [bx + si], al
  0008:0019  0000              add      byte ptr [bx + si], al
  0008:001B  0000              add      byte ptr [bx + si], al
  0008:001D  0000              add      byte ptr [bx + si], al
  0008:001F  0000              add      byte ptr [bx + si], al
  0008:0021  0000              add      byte ptr [bx + si], al
  0008:0023  0003              add      byte ptr [bp + di], al
  0008:0025  0000              add      byte ptr [bx + si], al
  0008:0027  44                inc      sp
  0008:0028  4d                dec      bp
  0008:0029  43                inc      bx
  0008:002A  53                push     bx
  0008:002B  52                push     dx
  0008:002C  0000              add      byte ptr [bx + si], al
  0008:002E  3200              xor      al, byte ptr [bx + si]
  0008:0030  47                inc      di
  0008:0031  00496e            add      byte ptr [bx + di + 0x6e], cl
  0008:0034  636f6d            arpl     word ptr [bx + 0x6d], bp
  0008:0037  7061              jo       0x11a
  0008:0039  7469              je       0x124
  0008:003B  626c65            bound    bp, dword ptr [si + 0x65]
  0008:003E  205072            and      byte ptr [bx + si + 0x72], dl
  0008:0041  6f                outsw    dx, word ptr [si]
  0008:0042  677261            jb       0x126
  0008:0045  6d                insw     word ptr es:[di], dx
  0008:0046  005468            add      byte ptr [si + 0x68], dl
  0008:0049  6973207072        imul     si, word ptr [bp + di + 0x20], 0x7270
  0008:004E  6f                outsw    dx, word ptr [si]
  0008:004F  677261            jb       0x133
  0008:0052  6d                insw     word ptr es:[di], dx
  0008:0053  206361            and      byte ptr [bp + di + 0x61], ah
  0008:0056  6e                outsb    dx, byte ptr [si]
  0008:0057  6e                outsb    dx, byte ptr [si]
  0008:0058  6f                outsw    dx, word ptr [si]
  0008:0059  7420              je       0xfb
  0008:005B  7275              jb       0x152
  0008:005D  6e                outsb    dx, byte ptr [si]
  0008:005E  207769            and      byte ptr [bx + 0x69], dh
  0008:0061  7468              je       0x14b
  0008:0063  207468            and      byte ptr [si + 0x68], dh
  0008:0066  6973207665        imul     si, word ptr [bp + di + 0x20], 0x6576
  0008:006B  7273              jb       0x160
  0008:006D  696f6e206f        imul     bp, word ptr [bx + 0x6e], 0x6f20
  0008:0072  66204465          and      byte ptr [si + 0x65], al
  0008:0076  736b              jae      0x163
  0008:0078  4d                dec      bp
  0008:0079  61                popaw    
  0008:007A  7465              je       0x161
  0008:007C  2e2020            and      byte ptr cs:[bx + si], ah
  0008:007F  50                push     ax
  0008:0080  6c                insb     byte ptr es:[di], dx
  0008:0081  6561              popaw    
  0008:0083  7365              jae      0x16a
  0008:0085  206f62            and      byte ptr [bx + 0x62], ch
  0008:0088  7461              je       0x16b
  0008:008A  696e207468        imul     bp, word ptr [bp + 0x20], 0x6874
  0008:008F  65207570          and      byte ptr gs:[di + 0x70], dh
  0008:0093  6461              popaw    
  0008:0095  7465              je       0x17c
  0008:0097  64207665          and      byte ptr fs:[bp + 0x65], dh
  0008:009B  7273              jb       0x190
  0008:009D  696f6e206f        imul     bp, word ptr [bx + 0x6e], 0x6f20
  0008:00A2  662000            and      byte ptr [bx + si], al
  0008:00A5  0000              add      byte ptr [bx + si], al
  0008:00A7  0000              add      byte ptr [bx + si], al
  0008:00A9  0000              add      byte ptr [bx + si], al
  0008:00AB  0000              add      byte ptr [bx + si], al
  0008:00AD  0000              add      byte ptr [bx + si], al
  0008:00AF  0000              add      byte ptr [bx + si], al
  0008:00B1  db 00                                              ; |.|