; ========================================================================
; Disassembly of /Users/joe/Documents/GitHub/bayside/archive/deskmate-3.05/extracted/DMEMM.RES
; Generated by disasm_mz.py (Bayside project)
; ========================================================================

; MZ Header:
;   File size:        2582 bytes
;   Header size:      512 bytes
;   Code size:        2070 bytes
;   Pages:            6
;   Relocations:      6
;   Entry point:      0000:0000
;   Init SS:SP:       001A:0002
;   Min alloc:        0x0000 paragraphs
;   Max alloc:        0x0001 paragraphs
;   DM89 signature:   present
;   DM89 raw:         444d38393e1e013e0000000000000000000000000000000000000000000000000001

; Segment Map:
;   seg_0000  file=0x0200  (CODE/DATA)
;   seg_001A  file=0x03A0  (CODE/DATA)
;   seg_0070  file=0x0900  (CODE/DATA)
;   seg_007A  file=0x09A0  (CODE/DATA)

; Relocation Table (6 entries):
;   001A:0017  file=0x03B7  value=seg_0070
;   001A:0043  file=0x03E3  value=seg_001A
;   0000:0001  file=0x0201  value=seg_0070
;   007A:004A  file=0x09EA  value=seg_001A
;   0000:0175  file=0x0375  value=seg_001A
;   001A:0266  file=0x0606  value=seg_0000

; String Table:
;   001A:0034 (0x03D4): "DMEMM$"
;   001A:0083 (0x0423): "VRQS"
;   001A:00A5 (0x0445): "[YZ^"
;   001A:00AB (0x044B): "QRVW:"
;   001A:00F8 (0x0498): "_^ZY"
;   001A:039C (0x073C): "VSQR"
;   001A:0403 (0x07A3): "sSWUQP3"
;   001A:0443 (0x07E3): "ZXZY]_"
;   001A:0459 (0x07F9): "VWUP"
;   001A:0472 (0x0812): "X]_^"
;   001A:0506 (0x08A6): "Dr%&"
;   0070:0075 (0x0975): "t\r&9"
;   007A:0038 (0x09D8): "EMMXXXX0DMEMM"

; Analysis Summary:
;   Instructions:     183
;   Functions (CALL): 1
;   Jump targets:     12
;   Strings:          13
;   INT calls:        22

; ========================================================================
; CODE / DATA
; ========================================================================

; ------------------------------------------------------------------------
; SEGMENT seg_0000  (416 bytes, file 0x0200-0x03A0)
; ------------------------------------------------------------------------
seg_0000:


entry_point:
  0000:0000  b87000            mov      ax, 0x70  ; RELOC->seg_0070
  0000:0003  8ec0              mov      es, ax
  0000:0005  bbe000            mov      bx, 0xe0
  0000:0008  268c5f20          mov      word ptr es:[bx + 0x20], ds
  0000:000C  8ed8              mov      ds, ax
  0000:000E  b80006            mov      ax, 0x600
  0000:0011  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:0013  a90080            test     ax, 0x8000
  0000:0016  b8f001            mov      ax, 0x1f0
  0000:0019  7503              jne      0x1e  ; -> loc_0000_001E
  0000:001B  b8ff01            mov      ax, 0x1ff

loc_0000_001E:
  0000:001E  cde0              int      0xe0  ; INT E0h, AH=01h
  0000:0020  b82f35            mov      ax, 0x352f
  0000:0023  cd21              int      0x21  ; INT 21h/35h: Get interrupt vector
  0000:0025  8cc0              mov      ax, es
  0000:0027  0bc3              or       ax, bx
  0000:0029  742a              je       0x55  ; -> loc_0000_0055
  0000:002B  b80043            mov      ax, 0x4300
  0000:002E  cd2f              int      0x2f  ; INT 2Fh, AH=43h
  0000:0030  3c80              cmp      al, 0x80
  0000:0032  7521              jne      0x55  ; -> loc_0000_0055
  0000:0034  b81043            mov      ax, 0x4310
  0000:0037  cd2f              int      0x2f  ; INT 2Fh, AH=43h
  0000:0039  891e0200          mov      word ptr [2], bx
  0000:003D  8c060400          mov      word ptr [4], es
  0000:0041  b410              mov      ah, 0x10
  0000:0043  baffff            mov      dx, 0xffff
  0000:0046  ff1e0200          lcall    [2]
  0000:004A  80fbb0            cmp      bl, 0xb0
  0000:004D  7406              je       0x55  ; -> loc_0000_0055
  0000:004F  c70604000000      mov      word ptr [4], 0

loc_0000_0055:
  0000:0055  b86735            mov      ax, 0x3567
  0000:0058  cd21              int      0x21  ; INT 21h/35h: Get interrupt vector
  0000:005A  bf0a00            mov      di, 0xa
  0000:005D  bed800            mov      si, 0xd8
  0000:0060  b90800            mov      cx, 8
  0000:0063  fc                cld      
  0000:0064  f3a6              repe cmpsb byte ptr [si], byte ptr es:[di]
  0000:0066  7519              jne      0x81  ; -> loc_0000_0081
  0000:0068  b440              mov      ah, 0x40
  0000:006A  cd67              int      0x67  ; INT 67h, AH=40h
  0000:006C  0ae4              or       ah, ah
  0000:006E  7511              jne      0x81  ; -> loc_0000_0081
  0000:0070  b442              mov      ah, 0x42
  0000:0072  cd67              int      0x67  ; INT 67h, AH=42h
  0000:0074  0ae4              or       ah, ah
  0000:0076  7509              jne      0x81  ; -> loc_0000_0081
  0000:0078  83fb04            cmp      bx, 4
  0000:007B  7204              jb       0x81  ; -> loc_0000_0081
  0000:007D  891e0600          mov      word ptr [6], bx

loc_0000_0081:
  0000:0081  a10001            mov      ax, word ptr [0x100]
  0000:0084  8ec0              mov      es, ax
  0000:0086  268b1e0200        mov      bx, word ptr es:[2]
  0000:008B  2bd8              sub      bx, ax
  0000:008D  8bd3              mov      dx, bx
  0000:008F  a10400            mov      ax, word ptr [4]
  0000:0092  0b060600          or       ax, word ptr [6]
  0000:0096  7405              je       0x9d  ; -> loc_0000_009D
  0000:0098  b80031            mov      ax, 0x3100
  0000:009B  cd21              int      0x21  ; INT 21h/31h: TSR (keep process)

loc_0000_009D:
  0000:009D  b85931            mov      ax, 0x3159
  0000:00A0  cd21              int      0x21  ; INT 21h/31h: TSR (keep process)
  0000:00A2  53                push     bx
  0000:00A3  51                push     cx
  0000:00A4  52                push     dx
  0000:00A5  56                push     si
  0000:00A6  57                push     di
  0000:00A7  b451              mov      ah, 0x51
  0000:00A9  cd21              int      0x21  ; INT 21h/51h: Get PSP
  0000:00AB  53                push     bx
  0000:00AC  8b1e0001          mov      bx, word ptr [0x100]
  0000:00B0  b450              mov      ah, 0x50
  0000:00B2  cd21              int      0x21  ; INT 21h/50h: Set PSP
  0000:00B4  833e060000        cmp      word ptr [6], 0
  0000:00B9  7446              je       0x101  ; -> loc_0000_0101
  0000:00BB  b80d06            mov      ax, 0x60d
  0000:00BE  cde0              int      0xe0  ; INT E0h, AH=06h
  0000:00C0  3d0d44            cmp      ax, 0x440d
  0000:00C3  723c              jb       0x101  ; -> loc_0000_0101
  0000:00C5  b441              mov      ah, 0x41
  0000:00C7  cd67              int      0x67  ; INT 67h, AH=41h
  0000:00C9  0ae4              or       ah, ah
  0000:00CB  7534              jne      0x101  ; -> loc_0000_0101
  0000:00CD  891e1601          mov      word ptr [0x116], bx
  0000:00D1  b90400            mov      cx, 4
  0000:00D4  be1a01            mov      si, 0x11a
  0000:00D7  890c              mov      word ptr [si], cx
  0000:00D9  83c602            add      si, 2
  0000:00DC  891c              mov      word ptr [si], bx
  0000:00DE  81c30004          add      bx, 0x400
  0000:00E2  e2f5              loop     0xd9
  0000:00E4  b8024f            mov      ax, 0x4f02
  0000:00E7  88260d00          mov      byte ptr [0xd], ah
  0000:00EB  bb0400            mov      bx, 4
  0000:00EE  cd67              int      0x67  ; INT 67h, AH=4Fh
  0000:00F0  0ae4              or       ah, ah
  0000:00F2  740f              je       0x103  ; -> loc_0000_0103
  0000:00F4  b8034e            mov      ax, 0x4e03
  0000:00F7  88260d00          mov      byte ptr [0xd], ah
  0000:00FB  cd67              int      0x67  ; INT 67h, AH=4Eh
  0000:00FD  0ae4              or       ah, ah
  0000:00FF  7402              je       0x103  ; -> loc_0000_0103

loc_0000_0101:
  0000:0101  eb76              jmp      0x179  ; -> loc_0000_0179

loc_0000_0103:
  0000:0103  a21801            mov      byte ptr [0x118], al
  0000:0106  b443              mov      ah, 0x43
  0000:0108  bb0400            mov      bx, 4
  0000:010B  8bcb              mov      cx, bx
  0000:010D  cd67              int      0x67  ; INT 67h, AH=43h
  0000:010F  0ae4              or       ah, ah
  0000:0111  7566              jne      0x179  ; -> loc_0000_0179
  0000:0113  b447              mov      ah, 0x47
  0000:0115  cd67              int      0x67  ; INT 67h, AH=47h
  0000:0117  0ae4              or       ah, ah
  0000:0119  755e              jne      0x179  ; -> loc_0000_0179
  0000:011B  b80050            mov      ax, 0x5000
  0000:011E  be0501            mov      si, 0x105
  0000:0121  cd67              int      0x67  ; INT 67h, AH=50h
  0000:0123  0ae4              or       ah, ah
  0000:0125  7402              je       0x129  ; -> loc_0000_0129
  0000:0127  33f6              xor      si, si

loc_0000_0129:
  0000:0129  89362401          mov      word ptr [0x124], si
  0000:012D  b448              mov      ah, 0x48
  0000:012F  cd67              int      0x67  ; INT 67h, AH=48h
  0000:0131  b445              mov      ah, 0x45
  0000:0133  cd67              int      0x67  ; INT 67h, AH=45h
  0000:0135  32e4              xor      ah, ah
  0000:0137  a01801            mov      al, byte ptr [0x118]
  0000:013A  0402              add      al, 2
  0000:013C  8b0e0600          mov      cx, word ptr [6]
  0000:0140  83c105            add      cx, 5
  0000:0143  8bd9              mov      bx, cx
  0000:0145  83f919            cmp      cx, 0x19
  0000:0148  7202              jb       0x14c  ; -> loc_0000_014C
  0000:014A  b119              mov      cl, 0x19

loc_0000_014C:
  0000:014C  f6e1              mul      cl
  0000:014E  d1e0              shl      ax, 1
  0000:0150  a30800            mov      word ptr [8], ax
  0000:0153  43                inc      bx
  0000:0154  d1eb              shr      bx, 1
  0000:0156  81fbfe00          cmp      bx, 0xfe
  0000:015A  7203              jb       0x15f  ; -> loc_0000_015F
  0000:015C  bbfe00            mov      bx, 0xfe

loc_0000_015F:
  0000:015F  881e0c00          mov      byte ptr [0xc], bl
  0000:0163  b103              mov      cl, 3
  0000:0165  d3e3              shl      bx, cl
  0000:0167  03c3              add      ax, bx
  0000:0169  050f00            add      ax, 0xf
  0000:016C  fec1              inc      cl
  0000:016E  d3e8              shr      ax, cl
  0000:0170  8bd8              mov      bx, ax
  0000:0172  9a54021a00        lcall    0x1a, 0x254  ; -> sub_0000_001A | RELOC->seg_001A
  0000:0177  7304              jae      0x17d  ; -> loc_0000_017D

loc_0000_0179:
  0000:0179  b401              mov      ah, 1
  0000:017B  eb12              jmp      0x18f  ; -> loc_0000_018F

loc_0000_017D:
  0000:017D  a30a00            mov      word ptr [0xa], ax
  0000:0180  8ec0              mov      es, ax
  0000:0182  b103              mov      cl, 3
  0000:0184  d3e3              shl      bx, cl
  0000:0186  8bcb              mov      cx, bx
  0000:0188  fc                cld      
  0000:0189  33c0              xor      ax, ax
  0000:018B  33ff              xor      di, di
  0000:018D  f3ab              rep stosw word ptr es:[di], ax

loc_0000_018F:
  0000:018F  5b                pop      bx
  0000:0190  50                push     ax
  0000:0191  b450              mov      ah, 0x50
  0000:0193  cd21              int      0x21  ; INT 21h/50h: Set PSP
  0000:0195  0e                push     cs
  0000:0196  07                pop      es
  0000:0197  58                pop      ax
  0000:0198  5f                pop      di
  0000:0199  5e                pop      si
  0000:019A  5a                pop      dx
  0000:019B  59                pop      cx
  0000:019C  5b                pop      bx
  0000:019D  cb                retf     
  0000:019E  db 00 00                                           ; |..|

; ------------------------------------------------------------------------
; SEGMENT seg_001A  (1376 bytes, file 0x03A0-0x0900)
; ------------------------------------------------------------------------
seg_001A:

  001A:0000  db 00 00 00 00 00 00 00 3C 19 72 07 B8 FF FF F9 CB ; |.......<.r......|
  001A:0010  db 1F CB 1E 53 53 55 BB 70 00 8E DB 8B EC C7 46 04 ; |...SSU.p......F.| [RELOC->seg_0070]
  001A:0020  db 10 00 8A D8 32 FF 03 DB 8B 9F A6 00 87 5E 02 5D ; |....2........^.]|
  001A:0030  db C3 EB 07 90                                     ; |....|
  001A:0034  db 44 4D 45 4D 4D 24                               ; "DMEMM$"
  001A:003A  db FB 80 FC 4D 75 0F 9A 07 00 1A 00                ; |...Mu......| [RELOC->seg_001A]
  001A:0045  55                push     bp
  001A:0046  8bec              mov      bp, sp
  001A:0048  f8                clc      
  001A:0049  9c                pushf    
  001A:004A  8f4606            pop      word ptr [bp + 6]
  001A:004D  5d                pop      bp
  001A:004E  cf                iret     
  001A:004F  db 2E 80 3E 06 00 FF 75 F7 2E FF 2E 02 00 26 8A 4C ; |..>...u......&.L|
  001A:005F  db 04 32 ED 8B 36 24 01 0B F6 74 0C 80 F9 01 74 07 ; |.2..6$...t....t.|
  001A:006F  db B8 00 50 CD 67 EB 0C 8B D9 FE CB 8A C3 B4 44 CD ; |..P.g.........D.|
  001A:007F  db 67 E2 F6 C3                                     ; |g...|
  001A:0083  db 56 52 51 53                                     ; "VRQS"
  001A:0087  db 06 3A 16 0C 00 73 16 32 F6 8B F2 B1 03 D3 E6 03 ; |.:...s.2........|
  001A:0097  db 36 08 00 8E 06 0A 00 26 8B 14 E8 B8 FF 07       ; |6......&......|
  001A:00A5  db 5B 59 5A 5E                                     ; "[YZ^"
  001A:00A9  db C3 06                                           ; |..|
  001A:00AB  db 51 52 56 57 3A                                  ; "QRVW:"
  001A:00B0  db 16 0C 00 73 3D 8E 06 0A 00 33 FF B6 80 32 ED 8A ; |...s=....3...2..|
  001A:00C0  db 0E 18 01 80 C1 02 B0 01 FE C6 03 F9 3B 3E 08 00 ; |............;>..|
  001A:00D0  db 73 20 26 86 05 0A C0 75 EF 26 88 55 01 83 C7 02 ; |s &....u.&.U....|
  001A:00E0  db 8A 26 0D 00 BE 1A 01 CD 67 0A E4 74 09 26 C6 45 ; |.&......g..t.&.E|
  001A:00F0  db FE 00 33 C0 EB 02 8A C6                         ; |..3.....|
  001A:00F8  db 5F 5E 5A 59                                     ; "_^ZY"
  001A:00FC  db 07 C3 E8 A9 FF 0B C0 74 05 50 E8 7A FF 58 C3 E8 ; |.......t.P.z.X..|
  001A:010C  db 29 00 72 04 C6 44 FE 00 1F 5E C3 E8 1D 00 72 0A ; |).r..D...^....r.|
  001A:011C  db CD 67 8A C4 FE C0 0A E4 74 EE 33 C0 EB EA E8 0A ; |.g......t.3.....|
  001A:012C  db 00 72 F7 CD 67 C6 44 FE 00 EB E7 58 56 1E 50 51 ; |.r..g.D....XV.PQ|
  001A:013C  db 80 FA 80 72 23 8A 0E 18 01 80 C1 02 8A C2 2C 80 ; |...r#.........,.|
  001A:014C  db F6 E1 8B F0 3B 36 08 00 F5 72 0D 83 C6 02 8A 26 ; |....;6...r.....&|
  001A:015C  db 0D 00 B0 01 8E 1E 0A 00 59 C3 33 C0 38 06 0E 00 ; |........Y.3.8...|
  001A:016C  db 75 0D 39 06 04 00 74 07 C6 06 E0 00 23 F8 C3 F9 ; |u.9...t.....#...|
  001A:017C  db C3 C6 06 E0 00 44 C3 06 52 53 33 D2 83 3E 04 00 ; |.....D..RS3..>..|
  001A:018C  db 00 74 46 8B D3 42 75 01 4A B4 10 FF 1E 02 00 3D ; |.tF..Bu.J......=|
  001A:019C  db 01 00 74 09 80 FB B0 74 30 33 D2 EB 2C 8E C3 26 ; |..t....t03..,..&|
  001A:01AC  db C6 06 00 00 5A B4 51 CD 21 26 89 1E 01 00 4A 26 ; |....Z.Q.!&....J&|
  001A:01BC  db 89 16 03 00 8C C0 87 06 00 00 26 A3 05 00 8C C0 ; |..........&.....|
  001A:01CC  db 40 8B DA 83 C4 02 F8 EB 0F 5B B4 48 CD 21 73 08 ; |@........[.H.!s.|
  001A:01DC  db 3B DA 73 03 8B DA 4B F9 5A 07 C3 06 53 52 33 C0 ; |;.s...K.Z...SR3.|
  001A:01EC  db 8B 16 00 00 8C C3 4B 0B D2 74 2F 3B D3 74 0B 8E ; |......K..t/;.t..|
  001A:01FC  db C2 8B C2 26 8B 16 05 00 EB ED 8E C2 26 8B 1E 05 ; |...&........&...|
  001A:020C  db 00 0B C0 74 09 8E C0 26 89 1E 05 00 EB 04 89 1E ; |...t...&........|
  001A:021C  db 00 00 B4 11 FF 1E 02 00 EB 07 43 8E C3 B4 49 CD ; |..........C...I.|
  001A:022C  db 21 5A 5B 07 C3 8B 1E 00 00 C3 A1 00 00 0B C0 75 ; |!Z[............u|
  001A:023C  db 05 89 1E 00 00 C3 06 8E C0 26 A1 05 00 0B C0 75 ; |.........&.....u|
  001A:024C  db F6 26 89 1E 05 00 07 C3 E8 2C FF CB 06 53 56 57 ; |.&.......,...SVW|
  001A:025C  db 80 3E 0E 00 00 75 0C 9A A2 00 00 00 0A E4 75 24 ; |.>...u........u$| [RELOC->seg_0000]
  001A:026C  db E8 78 FF 8E 06 0A 00 33 FF 26 C6 05 01 26 C6 45 ; |.x.....3.&...&.E|
  001A:027C  db 01 FF 83 C7 02 8A 26 0D 00 32 C0 BE 1A 01 CD 67 ; |......&..2.....g|
  001A:028C  db 0A E4 74 0E C7 06 06 00 00 00 83 3E 04 00 00 77 ; |..t........>...w|
  001A:029C  db 01 F9 5F 5E 5B 07 C3 06 56 51 52 83 3E 06 00 00 ; |.._^[...VQR.>...|
  001A:02AC  db 74 4C 81 FB 00 10 77 46 81 C3 FF 03 B1 0A D3 EB ; |tL....wF........|
  001A:02BC  db B4 43 CD 67 0A E4 75 36 8A CB B4 51 CD 21 8B 36 ; |.C.g..u6...Q.!.6|
  001A:02CC  db 08 00 8E 06 0A 00 33 C0 26 38 64 04 75 11 26 88 ; |......3.&8d.u.&.|
  001A:02DC  db 4C 04 26 89 5C 02 26 89 14 8B 1E 16 01 EB 14 83 ; |L.&.\.&.........|
  001A:02EC  db C6 08 FE C0 3A 06 0C 00 72 DE B4 45 CD 67 B8 FF ; |....:...r..E.g..|
  001A:02FC  db 00 33 DB 5A 59 5E 07 C3 83 3E 06 00 00 74 06 3A ; |.3.ZY^...>...t.:|
  001A:030C  db 26 0C 00 72 02 F9 C3 06 56 50 E8 0C 00 58 26 8A ; |&..r....VP...X&.|
  001A:031C  db 44 04 26 8B 5C 02 5E 07 C3 51 8A C4 32 E4 8B F0 ; |D.&.\.^..Q..2...|
  001A:032C  db B1 03 D3 E6 03 36 08 00 8E 06 0A 00 59 C3 53 B4 ; |.....6......Y.S.|
  001A:033C  db 51 CD 21 E8 02 00 5B C3 06 56 83 3E 06 00 00 74 ; |Q.!...[..V.>...t|
  001A:034C  db 21 8B 36 08 00 8E 06 0A 00 33 C0 26 38 64 04 74 ; |!.6......3.&8d.t|
  001A:035C  db 06 26 39 5C 02 74 0D 83 C6 08 FE C0 3A 06 0C 00 ; |.&9\.t......:...|
  001A:036C  db 72 E9 B0 FF 5E 07 C3 06 56 52 E8 AC FF 26 8B 14 ; |r...^...VR...&..|
  001A:037C  db B4 45 CD 67 26 C6 44 04 00 5A EB E8 06 56 E8 98 ; |.E.g&.D..Z...V..|
  001A:038C  db FF 26 89 5C 02 EB DD 80 FC FF 75 03 33 C0 C3 06 ; |.&.\......u.3...|
  001A:039C  db 56 53 51 52                                     ; "VSQR"
  001A:03A0  db E8 82 FF 26 8B 14 B4 47 CD 67 E8 AF FC 8B C2 5A ; |...&...G.g.....Z|
  001A:03B0  db 59 5B EB BC E8 DC FF 51 51 1E 8E DA FC F3 A4 1F ; |Y[.....QQ.......|
  001A:03C0  db 59 52 9C 0B C0 74 06 8B D0 B4 48 CD 67 9D 5A 58 ; |YR...t....H.g.ZX|
  001A:03D0  db C3 0B D2 75 7A 80 FC FF 74 75 8B 16 16 01 3B FA ; |...uz...tu....;.|
  001A:03E0  db 72 6B 81 C2 00 10 3B FA 73 63 06 4E 8E C6 26 8B ; |rk....;.sc.N..&.|
  001A:03F0  db 16 03 00 46 07 81 FA 00 10 73 5D 51 B1 04 D3 E2 ; |...F.....s]Q....|
  001A:0400  db 59 3B D1                                        ; |Y;.|
  001A:0403  db 73 53 57 55 51 50 33                            ; "sSWUQP3"
  001A:040A  db C0 50 52 8B EC 8B CA 8B 46 04 E8 41 00 72 24 01 ; |.PR.....F..A.r$.|
  001A:041A  db 46 02 3B C1 75 22 8B 46 02 8B 56 06 2B D0 74 19 ; |F.;.u".F..V.+.t.|
  001A:042A  db 8B C1 B1 04 D3 E8 03 F8 8B 4E 00 3B CA 76 D8 8B ; |.........N.;.v..|
  001A:043A  db CA EB D4 89 46 02 EB 01 F8                      ; |....F....|
  001A:0443  db 5A 58 5A 59 5D 5F                               ; "ZXZY]_"
  001A:0449  db BA 00 00 C3 33 D2 1E 8E DF B4 3F CD 21 1F C3 06 ; |....3.....?.!...|
  001A:0459  db 56 57 55 50                                     ; "VWUP"
  001A:045D  db 8E C7 8B FE E8 E9 FF 8B EC 87 46 00 9C 33 FF 87 ; |..........F..3..|
  001A:046D  db D6 E8 43 FF 9D                                  ; |..C..|
  001A:0472  db 58 5D 5F 5E                                     ; "X]_^"
  001A:0476  db 07 C3 E8 18 FF 26 FF 35 E9 40 FF E8 0F FF 26 89 ; |.....&.5.@....&.|
  001A:0486  db 0D 51 E9 36 FF 06 52 8B 16 00 00 0B D2 74 1D 8E ; |.Q.6..R......t..|
  001A:0496  db C2 26 A1 01 00 3B C3 74 0B 0B C0 74 07 26 8B 16 ; |.&...;.t...t.&..|
  001A:04A6  db 05 00 EB E7 42 8E C2 E8 37 FD EB DB E8 8F FE 3C ; |....B...7......<|
  001A:04B6  db FF 74 05 8A E0 E8 B5 FE 5A 07 C3 06 53 3B 1E 16 ; |.t......Z...S;..|
  001A:04C6  db 01 75 05 B8 02 00 EB 1C 4B A1 00 00 0B C0 74 11 ; |.u......K.....t.|
  001A:04D6  db 3B C3 74 08 8E C0 26 A1 05 00 EB F0 B8 01 00 EB ; |;.t...&.........|
  001A:04E6  db 03 B8 00 00 5B 07 C3 56 57 51 08 26 0E 00 80 3E ; |....[..VWQ.&...>|
  001A:04F6  db 0E 00 00 74 37 0A E4 74 2F B8 0D 06 CD E0 3D 0F ; |...t7..t/.....=.|
  001A:0506  db 44 72 25 26                                     ; "Dr%&"
  001A:050A  db 8B 07 2E A3 02 00 26 8B 4F 02 2E 89 0E 04 00 0B ; |......&.O.......|
  001A:051A  db C1 74 02 B0 FF 2E A2 06 00 FA 26 C7 07 31 00 26 ; |.t........&..1.&|
  001A:052A  db 8C 4F 02 FB 1E 07 EB 25 BB A6 00 83 C3 0F B1 04 ; |.O.....%........|
  001A:053A  db D3 EB B4 48 CD 21 73 06 33 DB 8E C3 EB 12 8E C0 ; |...H.!s.3.......|
  001A:054A  db B1 03 D3 E3 8B CB 33 F6 33 FF FC F3 A5 BB 10 00 ; |......3.3.......|
  001A:055A  db 59 5F 5E C3 00 00                               ; |Y_^...|

; ------------------------------------------------------------------------
; SEGMENT seg_0070  (160 bytes, file 0x0900-0x09A0)
; ------------------------------------------------------------------------
seg_0070:

  0070:0000  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................|
  0070:0010  db 0E 1F B4 51 CD 21 83 3E 06 00 00 74 41 8E 06 0A ; |...Q.!.>...tA...|
  0070:0020  db 00 8A 26 0D 00 B0 01 BE 02 00 1E 06 1F CD 67 1F ; |..&...........g.|
  0070:0030  db 8B 36 08 00 33 C9 26 38 6C 04 74 17 38 2E 0E 00 ; |.6..3.&8l.t.8...|
  0070:0040  db 74 06 26 39 5C 02 75 0B 26 8B 14 B4 45 CD 67 26 ; |t.&9\.u.&...E.g&|
  0070:0050  db 88 6C 04 83 C6 08 FE C1 3A 0E 0C 00 72 D8 8B 16 ; |.l......:...r...|
  0070:0060  db 00 00 33 FF 8A 0E 0E 00 0B D2 74 33 8E C2 26 8B ; |..3.......t3..&.|
  0070:0070  db 36 05 00 0A C9                                  ; |6....|
  0070:0075  db 74 0D 26 39                                     ; "t\r&9"
  0070:0079  db 1E 01 00 74 06 8B FA 8B D6 EB E4 B4 11 FF 1E 02 ; |...t............|
  0070:0089  db 00 8B D6 0B FF 75 06 89 36 00 00 EB D2 8E C7 26 ; |.....u..6......&|
  0070:0099  db 89 36 05 00 EB C9 8E                            ; |.6.....|

; ------------------------------------------------------------------------
; SEGMENT seg_007A  (118 bytes, file 0x09A0-0x0A16)
; ------------------------------------------------------------------------
seg_007A:

  007A:0000  db C3 B8 00 4C CD 21 83 00 AA 00 17 01 0B 01 FE 00 ; |...L.!..........|
  007A:0010  db 2A 01 3A 03 58 02 66 01 7D 01 83 01 E7 01 8B 04 ; |*.:.X.f.}.......|
  007A:0020  db 31 02 36 02 C1 04 73 03 88 03 ED 04 A3 02 78 04 ; |1.6...s.......x.|
  007A:0030  db 81 04 B4 03 D1 03 04 03                         ; |........|
  007A:0038  db 45 4D 4D 58 58 58 58 30 44 4D 45 4D 4D          ; "EMMXXXX0DMEMM"
  007A:0045  db 00                                                ; NUL
  007A:0046  db 00 00 07 00 1A 00 00 00 00 00 00 00 00 00 00 00 ; |................| [RELOC->seg_001A]
  007A:0056  db 00 00 00 00 00 00 00 00 00 00 00 00 03 00 07 00 ; |................|
  007A:0066  db 00 00 00 01 00 01 00 02 00 02 00 03 00 03 00 00 ; |................|