; ========================================================================
; Disassembly of /Users/joe/Documents/GitHub/bayside/archive/deskmate-3.05/extracted/DMTHES.RES
; Generated by disasm_mz.py (Bayside project)
; ========================================================================

; MZ Header:
;   File size:        1704 bytes
;   Header size:      512 bytes
;   Code size:        1192 bytes
;   Pages:            4
;   Relocations:      11
;   Entry point:      0000:002B
;   Init SS:SP:       004C:0002
;   Min alloc:        0x0000 paragraphs
;   Max alloc:        0x0001 paragraphs
;   DM89 signature:   present
;   DM89 raw:         444d38393e13013e00004d0000004d00000000000000000000000000000000000000

; Segment Map:
;   seg_0000  file=0x0200  (CODE/DATA)
;   seg_003A  file=0x05A0  (CODE/DATA)
;   seg_004C  file=0x06C0  (BSS)
;   seg_004D  file=0x06D0  (BSS)

; Relocation Table (11 entries):
;   003A:0010  file=0x05B0  value=seg_0000
;   003A:0014  file=0x05B4  value=seg_0000
;   0000:002C  file=0x022C  value=seg_003A
;   0000:004D  file=0x024D  value=seg_0000
;   0000:0057  file=0x0257  value=seg_0000
;   0000:005A  file=0x025A  value=seg_004D
;   0000:005D  file=0x025D  value=seg_0000
;   0000:01CE  file=0x03CE  value=seg_0000
;   0000:01FA  file=0x03FA  value=seg_0000
;   0000:0209  file=0x0409  value=seg_0000
;   0000:0215  file=0x0415  value=seg_0000

; String Table:
;   0000:02AA (0x04AA): "=D!~"
;   0000:0331 (0x0531): "F<7X"
;   0000:033C (0x053C): "!u9VWQR"
;   0000:035D (0x055D): "NOGF"
;   0000:0374 (0x0574): "ZY_^"
;   003A:0006 (0x05A6): "DMTHES"
;   003A:002B (0x05CB): "Thesaurus"
;   003A:0035 (0x05D5): "See your store or dealer for more information on obtaining this ..."
;   003A:0088 (0x0628): "PRGUF"
;   003A:0092 (0x0632): "DMGUF"
;   003A:00A6 (0x0646): "DMCSR"
;   003A:00B2 (0x0652): "DMTHES"
;   003A:00BC (0x065C): "1000CGA"
;   003A:00C4 (0x0664): "DDGAEGA"
;   003A:00CC (0x066C): "HERCPLANTC16TC4"
;   003A:00E0 (0x0680): "MCGAEGA"
;   003A:00E8 (0x0688): "LREST256TC40H"

; Analysis Summary:
;   Instructions:     42
;   Functions (CALL): 1
;   Jump targets:     1
;   Strings:          17
;   INT calls:        2

; ========================================================================
; CODE / DATA
; ========================================================================

; ------------------------------------------------------------------------
; SEGMENT seg_0000  (928 bytes, file 0x0200-0x05A0)
; ------------------------------------------------------------------------
seg_0000:


sub_0000_0000:
  0000:0000  57                push     di
  0000:0001  025d02            add      bl, byte ptr [di + 2]
  0000:0004  0000              add      byte ptr [bx + si], al
  0000:0006  cb                retf     
  0000:0007  db E8 B1 01 3D FF FF 74 1B E8 BE 00 3D FF FF 74 0D ; |...=..t....=..t.|
  0000:0017  db B8 7E 00 50 E8 07 02 83 C4 02 E8 EE 00 E8 AD 01 ; |.~.P............|
  0000:0027  db B8 FF FF C3                                     ; |....|

entry_point:
  0000:002B  b83a00            mov      ax, 0x3a  ; RELOC->seg_003A
  0000:002E  8ed8              mov      ds, ax
  0000:0030  8c060400          mov      word ptr [4], es
  0000:0034  2e8c1e0400        mov      word ptr cs:[4], ds
  0000:0039  89260801          mov      word ptr [0x108], sp
  0000:003D  8c160a01          mov      word ptr [0x10a], ss
  0000:0041  1e                push     ds
  0000:0042  07                pop      es
  0000:0043  bb0600            mov      bx, 6
  0000:0046  a10400            mov      ax, word ptr [4]
  0000:0049  894720            mov      word ptr [bx + 0x20], ax
  0000:004C  b90000            mov      cx, 0  ; RELOC->seg_0000
  0000:004F  b8ff01            mov      ax, 0x1ff
  0000:0052  cde0              int      0xe0  ; INT E0h, AH=01h
  0000:0054  9a07000000        lcall    0, 7  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:0059  b84d00            mov      ax, 0x4d  ; RELOC->seg_004D
  0000:005C  bb0000            mov      bx, 0  ; RELOC->seg_0000
  0000:005F  2bc3              sub      ax, bx
  0000:0061  051000            add      ax, 0x10
  0000:0064  8bd0              mov      dx, ax
  0000:0066  b0ff              mov      al, 0xff
  0000:0068  b431              mov      ah, 0x31
  0000:006A  cd21              int      0x21  ; INT 21h/31h: TSR (keep process)
  0000:006C  cb                retf     
  0000:006D  db CB 06 53 1E 07 B8 08 02 BA 88 00 BB 84 00 CD E0 ; |..S.............|
  0000:007D  db 0B C0 7E 16 C6 06 98 00 01 B8 06 02 CD E0 0B C0 ; |..~.............|
  0000:008D  db B8 FF FF 74 02 33 C0 5B 07 C3 BA 92 00 B8 08 02 ; |...t.3.[........|
  0000:009D  db CD E0 0B C0 7E DE C6 06 98 00 00 EB DC 52 06 80 ; |....~........R..|
  0000:00AD  db 3E 98 00 00 74 05 BA 88 00 EB 03 BA 92 00 B8 07 ; |>...t...........|
  0000:00BD  db 02 1E 07 CD E0 B8 36 01 A3 84 00 8C C8 A3 86 00 ; |......6.........|
  0000:00CD  db 07 5A C3 06 53 1E 07 BA 92 00 BB 8E 00 B8 06 02 ; |.Z..S...........|
  0000:00DD  db CD E0 0B C0 B8 FF FF 74 29 A1 8E 00 A3 84 00 A1 ; |.......t).......|
  0000:00ED  db 90 00 A3 86 00 B8 08 02 BA 88 00 BB 84 00 CD E0 ; |................|
  0000:00FD  db 0B C0 7E 07 C6 06 98 00 01 EB 05 C6 06 98 00 00 ; |..~.............|
  0000:010D  db 33 C0 5B 07 C3 52 BA 92 00 B8 07 02 06 1E 07 CD ; |3.[..R..........|
  0000:011D  db E0 07 B8 32 01 A3 8E 00 A3 84 00 8C C8 A3 90 00 ; |...2............|
  0000:012D  db A3 86 00 5A C3 B8 FF FF CB B8 FF FF CB 80 3E 98 ; |...Z..........>.|
  0000:013D  db 00 01 74 11 3D 39 00 7C 0C 74 07 3D 44 00 7E 2C ; |..t.=9.|.t.=D.~,|
  0000:014D  db EB 03 B8 AE 00 8F 06 9D 00 FF 36 9B 00 FF 36 9D ; |..........6...6.|
  0000:015D  db 00 53 8B DC 1E 06 16 07 FF 1E 84 00 07 1F 5B 8F ; |.S............[.|
  0000:016D  db 06 9D 00 8F 06 9B 00 FF 36 9D 00 C3 B8 FF FF EB ; |........6.......|
  0000:017D  db FA 80 3E 98 00 01 74 0A 3D BE 00 74 2C 3D BF 00 ; |..>...t.=..t,=..|
  0000:018D  db 74 27 8F 06 9D 00 FF 36 9B 00 FF 36 9D 00 53 8B ; |t'.....6...6..S.|
  0000:019D  db DC 1E 06 16 07 FF 1E 8E 00 07 1F 5B 8F 06 9D 00 ; |...........[....|
  0000:01AD  db 8F 06 9B 00 FF 36 9D 00 C3 B8 FF FF EB FA 06 53 ; |.....6.........S|
  0000:01BD  db 52 1E 07 BB A2 00 BA A6 00 B8 06 02 CD E0 9A 73 ; |R..............s|
  0000:01CD  db 02 00 00 5A 5B 07 C3 06 52 1E 07 BA A6 00 B8 07 ; |...Z[...R.......| [RELOC->seg_0000]
  0000:01DD  db 02 CD E0 5A 07 C3 E8 D5 FF E8 30 00 C3 E8 32 00 ; |...Z......0...2.|
  0000:01ED  db E8 E4 FF C3                                     ; |....|
  0000:01F1  55                push     bp
  0000:01F2  8bec              mov      bp, sp
  0000:01F4  83c504            add      bp, 4
  0000:01F7  9a9a020000        lcall    0, 0x29a  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:01FC  3dffff            cmp      ax, 0xffff
  0000:01FF  7416              je       0x217  ; -> loc_0000_0217
  0000:0201  3dfeff            cmp      ax, 0xfffe
  0000:0204  7411              je       0x217  ; -> loc_0000_0217
  0000:0206  9ac9020000        lcall    0, 0x2c9  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:020B  a3ac00            mov      word ptr [0xac], ax
  0000:020E  ff1ea200          lcall    [0xa2]
  0000:0212  9af3020000        lcall    0, 0x2f3  ; -> sub_0000_0000 | RELOC->seg_0000

loc_0000_0217:
  0000:0217  5d                pop      bp
  0000:0218  c3                ret      
  0000:0219  db B8 D6 20 E9 D2 FF B8 D7 20 E9 CC FF B8 E9 20 E9 ; |.. ..... ..... .|
  0000:0229  db C6 FF 06 53 52 1E 07 BA B2 00 BB AE 00 B8 06 02 ; |...SR...........|
  0000:0239  db CD E0 0B C0 B8 FF FF 74 02 33 C0 5A 5B 07 C3 52 ; |.......t.3.Z[..R|
  0000:0249  db BA B2 00 06 1E 07 B8 07 02 CD E0 07 5A C3 B8 00 ; |............Z...|
  0000:0259  db 00 EB 07 90 B8 01 00 EB 01 90 53 06 8B DC 83 C3 ; |..........S.....|
  0000:0269  db 06 16 07 FF 1E AE 00 07 5B C3 50 B8 D5 20 25 FF ; |........[.P.. %.|
  0000:0279  db 0F FF 1E A2 00 C7 06 BA 00 FF 0F 3C 20 7E 10 C7 ; |...........< ~..|
  0000:0289  db 06 BA 00 FF FF 3C 37 7E 06 C7 06 BA 00 FF EF 58 ; |.....<7~.......X|
  0000:0299  db CB 81 3E BA 00 FF 0F 74 11 81 3E BA 00 FF EF 74 ; |..>....t..>....t|
  0000:02A9  db 1E                                              ; |.|
  0000:02AA  db 3D 44 21 7E                                     ; "=D!~"
  0000:02AE  db 19 B8 FF FF CB 3D 0A 21 7F 05 23 06 BA 00 CB 3D ; |.....=.!..#....=|
  0000:02BE  db 2D 21 B8 FE FF 74 03 B8 FF FF CB 9C 3D 90 20 75 ; |-!...t......=. u|
  0000:02CE  db 22 81 3E BA 00 FF 0F 74 1A 50 B8 D5 20 FF 1E A2 ; |".>....t.P.. ...|
  0000:02DE  db 00 3C 29 58 7F 0D 53 8B 5D 0E 8B 1F D1 E3 43 29 ; |.<)X..S.].....C)|
  0000:02EE  db 5D 02 5B 9D CB 9C 81 3E AC 00 90 20 74 0A 81 3E ; |].[....>... t..>|
  0000:02FE  db AC 00 17 21 74 02 9D CB 81 3E BA 00 FF 0F 74 6A ; |...!t....>....tj|
  0000:030E  db 50 B8 D5 20 FF 1E A2 00 3C 29 7F 18 81 3E AC 00 ; |P.. ....<)...>..|
  0000:031E  db 17 21 74 10 58 53 8B 5D 0E 8B 1F D1 E3 43 01 5D ; |.!t.XS.].....C.]|
  0000:032E  db 02 5B EB                                        ; |.[.|
  0000:0331  db 46 3C 37 58                                     ; "F<7X"
  0000:0335  db 7F 41 81 3E AC 00 17                            ; |.A.>...|
  0000:033C  db 21 75 39 56 57 51 52                            ; "!u9VWQR"
  0000:0343  db 8B 76 00 83 C6 04 E8 2E 00 32 E4 B1 04 F6 E1 BF ; |.v.......2......|
  0000:0353  db BC 00 03 F8 B9 04 00 B8 00 00                   ; |..........|
  0000:035D  db 4E 4F 47 46                                     ; "NOGF"
  0000:0361  db 8A 15 0A 14 74 0D 8A 15 38 14 75 04 E2 F0 EB 03 ; |....t...8.u.....|
  0000:0371  db B8 FF FF                                        ; |...|
  0000:0374  db 5A 59 5F 5E                                     ; "ZY_^"
  0000:0378  db 9D CB 55 83 EC 0B 8B EC 1E 1E 07 16 1F 8D 46 00 ; |..U...........F.|
  0000:0388  db 55 50 8B EC B8 31 20 25 FF 0F 26 FF 1E A2 00 83 ; |UP...1 %..&.....|
  0000:0398  db C4 02 5D 1F 8A 46 00 83                         ; |..]..F..|

; ------------------------------------------------------------------------
; SEGMENT seg_003A  (264 bytes, file 0x05A0-0x06A8)
; ------------------------------------------------------------------------
seg_003A:

  003A:0000  db C4 0B 5D C3 00 00                               ; |..]...|
  003A:0006  db 44 4D 54 48 45 53                               ; "DMTHES"
  003A:000C  db 00                                                ; NUL
  003A:000D  db 00 6C 00 00 00 6D 00 00 00 00 00 00 00 00 00 00 ; |.l...m..........| [RELOC->seg_0000]
  003A:001D  db 00 00 00 00 00 00 00 00 00 00 00 03 00 00       ; |..............|
  003A:002B  db 54 68 65 73 61 75 72 75 73                      ; "Thesaurus"
  003A:0034  db 00                                                ; NUL
  003A:0035  db 53 65 65 20 79 6F 75 72 20 73 74 6F 72 65 20 6F ; "See your store or dealer for more information on obtaining t..."
  003A:0045  db 72 20 64 65 61 6C 65 72 20 66 6F 72 20 6D 6F 72
  003A:0055  db 65 20 69 6E 66 6F 72 6D 61 74 69 6F 6E 20 6F 6E
  003A:0065  db 20 6F 62 74 61 69 6E 69 6E 67 20 74 68 69 73 20
  003A:0075  db 70 72 6F 67 72 61 6D 2E
  003A:007D  db 00                                                ; NUL
  003A:007E  db 00 2B 00 35 00 00 CD AB BA DC                   ; |.+.5......|
  003A:0088  db 50 52 47 55 46                                  ; "PRGUF"
  003A:008D  db 00                                                ; NUL
  003A:008E  db CD AB BA DC                                     ; |....|
  003A:0092  db 44 4D 47 55 46                                  ; "DMGUF"
  003A:0097  db 00                                                ; NUL
  003A:0098  db 00 00 00 99 00 00 00 00 00 00 CD AB BA DC       ; |..............|
  003A:00A6  db 44 4D 43 53 52                                  ; "DMCSR"
  003A:00AB  db 00                                                ; NUL
  003A:00AC  db 00 00 CD AB BA DC                               ; |......|
  003A:00B2  db 44 4D 54 48 45 53                               ; "DMTHES"
  003A:00B8  db 00                                                ; NUL
  003A:00B9  db 00 00 00                                        ; |...|
  003A:00BC  db 31 30 30 30 43 47 41                            ; "1000CGA"
  003A:00C3  db 00                                                ; NUL
  003A:00C4  db 44 44 47 41 45 47 41                            ; "DDGAEGA"
  003A:00CB  db 00                                                ; NUL
  003A:00CC  db 48 45 52 43 50 4C 41 4E 54 43 31 36 54 43 34    ; "HERCPLANTC16TC4"
  003A:00DB  db 00                                                ; NUL
  003A:00DC  db 56 47 41 00                                     ; |VGA.|
  003A:00E0  db 4D 43 47 41 45 47 41                            ; "MCGAEGA"
  003A:00E7  db 00                                                ; NUL
  003A:00E8  db 4C 52 45 53 54 32 35 36 54 43 34 30 48          ; "LREST256TC40H"
  003A:00F5  db 00                                                ; NUL
  003A:00F6  db 00 00 43 00 00 00 4D 00 00 00 45 00 00 00 54 00 ; |..C...M...E...T.|
  003A:0106  db 00 00                                           ; |..|