; ========================================================================
; Disassembly of /Users/joe/Documents/GitHub/bayside/archive/deskmate-3.05/extracted/TRANSLAT.RES
; Generated by disasm_mz.py (Bayside project)
; ========================================================================

; MZ Header:
;   File size:        1586 bytes
;   Header size:      512 bytes
;   Code size:        1074 bytes
;   Pages:            4
;   Relocations:      7
;   Entry point:      0000:0026
;   Init SS:SP:       0044:0002
;   Min alloc:        0x0000 paragraphs
;   Max alloc:        0x0001 paragraphs
;   DM89 signature:   present
;   DM89 raw:         444d38393e1b013e0000450000004500000000000000000000000000000000000000

; Segment Map:
;   seg_0000  file=0x0200  (CODE/DATA)
;   seg_0033  file=0x0530  (CODE/DATA)
;   seg_0044  file=0x0640  (BSS)

; Relocation Table (7 entries):
;   0033:0016  file=0x0546  value=seg_0000
;   0000:0027  file=0x0227  value=seg_0033
;   0000:003B  file=0x023B  value=seg_0000
;   0000:01AC  file=0x03AC  value=seg_0000
;   0000:01D8  file=0x03D8  value=seg_0000
;   0000:01E7  file=0x03E7  value=seg_0000
;   0000:01F3  file=0x03F3  value=seg_0000

; String Table:
;   0000:0240 (0x0440): "=D!~"
;   0000:02C7 (0x04C7): "F<7X"
;   0000:02D2 (0x04D2): "!u9VWQR"
;   0000:02F3 (0x04F3): "NOGF"
;   0000:030A (0x050A): "ZY_^"
;   0033:000C (0x053C): "TRANSLATJ"
;   0033:0031 (0x0561): "Translate"
;   0033:003B (0x056B): "See your store or dealer for more information on obtaining this ..."
;   0033:008E (0x05BE): "PRGUF"
;   0033:0098 (0x05C8): "DMGUF"
;   0033:00AC (0x05DC): "DMCSR"
;   0033:00B6 (0x05E6): "1000CGA"
;   0033:00BE (0x05EE): "DDGAEGA"
;   0033:00C6 (0x05F6): "HERCPLANTC16TC4"
;   0033:00DA (0x060A): "MCGAEGA"
;   0033:00E2 (0x0612): "LREST256TC40H"

; Analysis Summary:
;   Instructions:     114
;   Functions (CALL): 7
;   Jump targets:     7
;   Strings:          16
;   INT calls:        7

; ========================================================================
; CODE / DATA
; ========================================================================

; ------------------------------------------------------------------------
; SEGMENT seg_0000  (816 bytes, file 0x0200-0x0530)
; ------------------------------------------------------------------------
seg_0000:


sub_0000_0000:
  0000:0000  0000              add      byte ptr [bx + si], al

sub_0000_0002:
  0000:0002  e89401            call     0x199  ; -> sub_0000_0199
  0000:0005  3dffff            cmp      ax, 0xffff
  0000:0008  741b              je       0x25  ; -> loc_0000_0025
  0000:000A  e8a100            call     0xae  ; -> sub_0000_00AE
  0000:000D  3dffff            cmp      ax, 0xffff
  0000:0010  740d              je       0x1f  ; -> loc_0000_001F
  0000:0012  b88400            mov      ax, 0x84
  0000:0015  50                push     ax
  0000:0016  e8ea01            call     0x203  ; -> sub_0000_0203
  0000:0019  83c402            add      sp, 2
  0000:001C  e8d100            call     0xf0  ; -> sub_0000_00F0

loc_0000_001F:
  0000:001F  e89001            call     0x1b2  ; -> sub_0000_01B2
  0000:0022  b8ffff            mov      ax, 0xffff

loc_0000_0025:
  0000:0025  c3                ret      

entry_point:
  0000:0026  b83300            mov      ax, 0x33  ; RELOC->seg_0033
  0000:0029  8ed8              mov      ds, ax
  0000:002B  8c060a00          mov      word ptr [0xa], es
  0000:002F  1e                push     ds
  0000:0030  07                pop      es
  0000:0031  bb0c00            mov      bx, 0xc
  0000:0034  a10a00            mov      ax, word ptr [0xa]
  0000:0037  894720            mov      word ptr [bx + 0x20], ax
  0000:003A  b90000            mov      cx, 0  ; RELOC->seg_0000
  0000:003D  b8ff01            mov      ax, 0x1ff
  0000:0040  cde0              int      0xe0  ; INT E0h, AH=01h
  0000:0042  e8bdff            call     2  ; -> sub_0000_0002
  0000:0045  b8ff4c            mov      ax, 0x4cff
  0000:0048  cd21              int      0x21  ; INT 21h/4Ch: Exit with return code
  0000:004A  cb                retf     
  0000:004B  db CB 06 53 1E 07 B8 08 02 BA 8E 00 BB 8A 00 CD E0 ; |..S.............|
  0000:005B  db 0B C0 7E 16 C6 06 9E 00 01 B8 06 02 CD E0 0B C0 ; |..~.............|
  0000:006B  db B8 FF FF 74 02 33 C0 5B 07 C3 BA 98 00 B8 08 02 ; |...t.3.[........|
  0000:007B  db CD E0 0B C0 7E DE C6 06 9E 00 00 EB DC 52 06 80 ; |....~........R..|
  0000:008B  db 3E 9E 00 00 74 05 BA 8E 00 EB 03 BA 98 00 B8 07 ; |>...t...........|
  0000:009B  db 02 1E 07 CD E0 B8 14 01 A3 8A 00 8C C8 A3 8C 00 ; |................|
  0000:00AB  db 07 5A C3                                        ; |.Z.|

sub_0000_00AE:
  0000:00AE  06                push     es
  0000:00AF  53                push     bx
  0000:00B0  1e                push     ds
  0000:00B1  07                pop      es
  0000:00B2  ba9800            mov      dx, 0x98
  0000:00B5  bb9400            mov      bx, 0x94
  0000:00B8  b80602            mov      ax, 0x206
  0000:00BB  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:00BD  0bc0              or       ax, ax
  0000:00BF  b8ffff            mov      ax, 0xffff
  0000:00C2  7429              je       0xed  ; -> loc_0000_00ED
  0000:00C4  a19400            mov      ax, word ptr [0x94]
  0000:00C7  a38a00            mov      word ptr [0x8a], ax
  0000:00CA  a19600            mov      ax, word ptr [0x96]
  0000:00CD  a38c00            mov      word ptr [0x8c], ax
  0000:00D0  b80802            mov      ax, 0x208
  0000:00D3  ba8e00            mov      dx, 0x8e
  0000:00D6  bb8a00            mov      bx, 0x8a
  0000:00D9  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:00DB  0bc0              or       ax, ax
  0000:00DD  7e07              jle      0xe6  ; -> loc_0000_00E6
  0000:00DF  c6069e0001        mov      byte ptr [0x9e], 1
  0000:00E4  eb05              jmp      0xeb  ; -> loc_0000_00EB

loc_0000_00E6:
  0000:00E6  c6069e0000        mov      byte ptr [0x9e], 0

loc_0000_00EB:
  0000:00EB  33c0              xor      ax, ax

loc_0000_00ED:
  0000:00ED  5b                pop      bx
  0000:00EE  07                pop      es
  0000:00EF  c3                ret      

sub_0000_00F0:
  0000:00F0  52                push     dx
  0000:00F1  ba9800            mov      dx, 0x98
  0000:00F4  b80702            mov      ax, 0x207
  0000:00F7  06                push     es
  0000:00F8  1e                push     ds
  0000:00F9  07                pop      es
  0000:00FA  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:00FC  07                pop      es
  0000:00FD  b81001            mov      ax, 0x110
  0000:0100  a39400            mov      word ptr [0x94], ax
  0000:0103  a38a00            mov      word ptr [0x8a], ax
  0000:0106  8cc8              mov      ax, cs
  0000:0108  a39600            mov      word ptr [0x96], ax
  0000:010B  a38c00            mov      word ptr [0x8c], ax
  0000:010E  5a                pop      dx
  0000:010F  c3                ret      
  0000:0110  db B8 FF FF CB B8 FF FF CB 80 3E 9E 00 01 74 11 3D ; |.........>...t.=|
  0000:0120  db 39 00 7C 0C 74 07 3D 44 00 7E 2C EB 03 B8 AE 00 ; |9.|.t.=D.~,.....|
  0000:0130  db 8F 06 A3 00 FF 36 A1 00 FF 36 A3 00 53 8B DC 1E ; |.....6...6..S...|
  0000:0140  db 06 16 07 FF 1E 8A 00 07 1F 5B 8F 06 A3 00 8F 06 ; |.........[......|
  0000:0150  db A1 00 FF 36 A3 00 C3 B8 FF FF EB FA 80 3E 9E 00 ; |...6.........>..|
  0000:0160  db 01 74 0A 3D BE 00 74 2C 3D BF 00 74 27 8F 06 A3 ; |.t.=..t,=..t'...|
  0000:0170  db 00 FF 36 A1 00 FF 36 A3 00 53 8B DC 1E 06 16 07 ; |..6...6..S......|
  0000:0180  db FF 1E 94 00 07 1F 5B 8F 06 A3 00 8F 06 A1 00 FF ; |......[.........|
  0000:0190  db 36 A3 00 C3 B8 FF FF EB FA                      ; |6........|

sub_0000_0199:
  0000:0199  06                push     es
  0000:019A  53                push     bx
  0000:019B  52                push     dx
  0000:019C  1e                push     ds
  0000:019D  07                pop      es
  0000:019E  bba800            mov      bx, 0xa8
  0000:01A1  baac00            mov      dx, 0xac
  0000:01A4  b80602            mov      ax, 0x206
  0000:01A7  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:01A9  9a09020000        lcall    0, 0x209  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:01AE  5a                pop      dx
  0000:01AF  5b                pop      bx
  0000:01B0  07                pop      es
  0000:01B1  c3                ret      

sub_0000_01B2:
  0000:01B2  06                push     es
  0000:01B3  52                push     dx
  0000:01B4  1e                push     ds
  0000:01B5  07                pop      es
  0000:01B6  baac00            mov      dx, 0xac
  0000:01B9  b80702            mov      ax, 0x207
  0000:01BC  cde0              int      0xe0  ; INT E0h, AH=02h
  0000:01BE  5a                pop      dx
  0000:01BF  07                pop      es
  0000:01C0  c3                ret      
  0000:01C1  db E8 D5 FF E8 30 00 C3 E8 32 00 E8 E4 FF C3       ; |....0...2.....|

loc_0000_01CF:
  0000:01CF  55                push     bp
  0000:01D0  8bec              mov      bp, sp
  0000:01D2  83c504            add      bp, 4
  0000:01D5  9a30020000        lcall    0, 0x230  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:01DA  3dffff            cmp      ax, 0xffff
  0000:01DD  7416              je       0x1f5  ; -> loc_0000_01F5
  0000:01DF  3dfeff            cmp      ax, 0xfffe
  0000:01E2  7411              je       0x1f5  ; -> loc_0000_01F5
  0000:01E4  9a5f020000        lcall    0, 0x25f  ; -> sub_0000_0000 | RELOC->seg_0000
  0000:01E9  a3b200            mov      word ptr [0xb2], ax
  0000:01EC  ff1ea800          lcall    [0xa8]
  0000:01F0  9a89020000        lcall    0, 0x289  ; -> sub_0000_0000 | RELOC->seg_0000

loc_0000_01F5:
  0000:01F5  5d                pop      bp
  0000:01F6  c3                ret      
  0000:01F7  db B8 D6 20 E9 D2 FF B8 D7 20 E9 CC FF             ; |.. ..... ...|

sub_0000_0203:
  0000:0203  b8e920            mov      ax, 0x20e9
  0000:0206  e9c6ff            jmp      0x1cf  ; -> loc_0000_01CF
  0000:0209  db 50 B8 D5 20 25 FF 0F FF 1E A8 00 C7 06 B4 00 FF ; |P.. %...........|
  0000:0219  db 0F 3C 20 7E 10 C7 06 B4 00 FF FF 3C 37 7E 06 C7 ; |.< ~.......<7~..|
  0000:0229  db 06 B4 00 FF EF 58 CB 81 3E B4 00 FF 0F 74 11 81 ; |.....X..>....t..|
  0000:0239  db 3E B4 00 FF EF 74 1E                            ; |>....t.|
  0000:0240  db 3D 44 21 7E                                     ; "=D!~"
  0000:0244  db 19 B8 FF FF CB 3D 0A 21 7F 05 23 06 B4 00 CB 3D ; |.....=.!..#....=|
  0000:0254  db 2D 21 B8 FE FF 74 03 B8 FF FF CB 9C 3D 90 20 75 ; |-!...t......=. u|
  0000:0264  db 22 81 3E B4 00 FF 0F 74 1A 50 B8 D5 20 FF 1E A8 ; |".>....t.P.. ...|
  0000:0274  db 00 3C 29 58 7F 0D 53 8B 5D 0E 8B 1F D1 E3 43 29 ; |.<)X..S.].....C)|
  0000:0284  db 5D 02 5B 9D CB 9C 81 3E B2 00 90 20 74 0A 81 3E ; |].[....>... t..>|
  0000:0294  db B2 00 17 21 74 02 9D CB 81 3E B4 00 FF 0F 74 6A ; |...!t....>....tj|
  0000:02A4  db 50 B8 D5 20 FF 1E A8 00 3C 29 7F 18 81 3E B2 00 ; |P.. ....<)...>..|
  0000:02B4  db 17 21 74 10 58 53 8B 5D 0E 8B 1F D1 E3 43 01 5D ; |.!t.XS.].....C.]|
  0000:02C4  db 02 5B EB                                        ; |.[.|
  0000:02C7  db 46 3C 37 58                                     ; "F<7X"
  0000:02CB  db 7F 41 81 3E B2 00 17                            ; |.A.>...|
  0000:02D2  db 21 75 39 56 57 51 52                            ; "!u9VWQR"
  0000:02D9  db 8B 76 00 83 C6 04 E8 2E 00 32 E4 B1 04 F6 E1 BF ; |.v.......2......|
  0000:02E9  db B6 00 03 F8 B9 04 00 B8 00 00                   ; |..........|
  0000:02F3  db 4E 4F 47 46                                     ; "NOGF"
  0000:02F7  db 8A 15 0A 14 74 0D 8A 15 38 14 75 04 E2 F0 EB 03 ; |....t...8.u.....|
  0000:0307  db B8 FF FF                                        ; |...|
  0000:030A  db 5A 59 5F 5E                                     ; "ZY_^"
  0000:030E  db 9D CB 55 83 EC 0B 8B EC 1E 1E 07 16 1F 8D 46 00 ; |..U...........F.|
  0000:031E  db 55 50 8B EC B8 31 20 25 FF 0F 26 FF 1E A8 00 83 ; |UP...1 %..&.....|
  0000:032E  db C4 02                                           ; |..|

; ------------------------------------------------------------------------
; SEGMENT seg_0033  (258 bytes, file 0x0530-0x0632)
; ------------------------------------------------------------------------
seg_0033:

  0033:0000  db 5D 1F 8A 46 00 83 C4 0B 5D C3 00 00             ; |]..F....]...|
  0033:000C  db 54 52 41 4E 53 4C 41 54 4A                      ; "TRANSLATJ"
  0033:0015  db 00                                                ; NUL
  0033:0016  db 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; |................| [RELOC->seg_0000]
  0033:0026  db 00 00 00 00 00 00 00 00 03 00 00                ; |...........|
  0033:0031  db 54 72 61 6E 73 6C 61 74 65                      ; "Translate"
  0033:003A  db 00                                                ; NUL
  0033:003B  db 53 65 65 20 79 6F 75 72 20 73 74 6F 72 65 20 6F ; "See your store or dealer for more information on obtaining t..."
  0033:004B  db 72 20 64 65 61 6C 65 72 20 66 6F 72 20 6D 6F 72
  0033:005B  db 65 20 69 6E 66 6F 72 6D 61 74 69 6F 6E 20 6F 6E
  0033:006B  db 20 6F 62 74 61 69 6E 69 6E 67 20 74 68 69 73 20
  0033:007B  db 70 72 6F 67 72 61 6D 2E
  0033:0083  db 00                                                ; NUL
  0033:0084  db 00 31 00 3B 00 00 CD AB BA DC                   ; |.1.;......|
  0033:008E  db 50 52 47 55 46                                  ; "PRGUF"
  0033:0093  db 00                                                ; NUL
  0033:0094  db CD AB BA DC                                     ; |....|
  0033:0098  db 44 4D 47 55 46                                  ; "DMGUF"
  0033:009D  db 00                                                ; NUL
  0033:009E  db 00 00 00 9F 00 00 00 00 00 00 CD AB BA DC       ; |..............|
  0033:00AC  db 44 4D 43 53 52                                  ; "DMCSR"
  0033:00B1  db 00                                                ; NUL
  0033:00B2  db 00 00 00 00                                     ; |....|
  0033:00B6  db 31 30 30 30 43 47 41                            ; "1000CGA"
  0033:00BD  db 00                                                ; NUL
  0033:00BE  db 44 44 47 41 45 47 41                            ; "DDGAEGA"
  0033:00C5  db 00                                                ; NUL
  0033:00C6  db 48 45 52 43 50 4C 41 4E 54 43 31 36 54 43 34    ; "HERCPLANTC16TC4"
  0033:00D5  db 00                                                ; NUL
  0033:00D6  db 56 47 41 00                                     ; |VGA.|
  0033:00DA  db 4D 43 47 41 45 47 41                            ; "MCGAEGA"
  0033:00E1  db 00                                                ; NUL
  0033:00E2  db 4C 52 45 53 54 32 35 36 54 43 34 30 48          ; "LREST256TC40H"
  0033:00EF  db 00                                                ; NUL
  0033:00F0  db 00 00 43 00 00 00 4D 00 00 00 45 00 00 00 54 00 ; |..C...M...E...T.|
  0033:0100  db 00 00                                           ; |..|